@startuml test
title Icon List
!define ICON_URL https://raw.githubusercontent.com/ThatGerber/plantuml-oci-icons/main/icons
!include ICON_URL/oci_2fa.puml.puml
!include ICON_URL/oci_api.puml.puml
!include ICON_URL/oci_authentication.puml.puml
!include ICON_URL/oci_batch.puml.puml
!include ICON_URL/oci_billing.puml.puml
!include ICON_URL/oci_cdn.puml.puml
!include ICON_URL/oci_cli.puml.puml
!include ICON_URL/oci_cloud.puml.puml
!include ICON_URL/oci_config.puml.puml
!include ICON_URL/oci_configservice.puml.puml
!include ICON_URL/oci_container.puml.puml
!include ICON_URL/oci_containerhost.puml.puml
!include ICON_URL/oci_containerimage.puml.puml
!include ICON_URL/oci_customer.puml.puml
!include ICON_URL/oci_database.puml.puml
!include ICON_URL/oci_debugging.puml.puml
!include ICON_URL/oci_desktop.puml.puml
!include ICON_URL/oci_developer.puml.puml
!include ICON_URL/oci_devices.puml.puml
!include ICON_URL/oci_disk.puml.puml
!include ICON_URL/oci_distribution.puml.puml
!include ICON_URL/oci_docdb.puml.puml
!include ICON_URL/oci_file.puml.puml
!include ICON_URL/oci_firewall.puml.puml
!include ICON_URL/oci_firewallrule.puml.puml
!include ICON_URL/oci_function.puml.puml
!include ICON_URL/oci_git.puml.puml
!include ICON_URL/oci_healthmonitoring.puml.puml
!include ICON_URL/oci_invoice.puml.puml
!include ICON_URL/oci_iot.puml.puml
!include ICON_URL/oci_key.puml.puml
!include ICON_URL/oci_key_vault.puml.puml
!include ICON_URL/oci_laptop.puml.puml
!include ICON_URL/oci_legacymainframe.puml.puml
!include ICON_URL/oci_loadbalancer.puml.puml
!include ICON_URL/oci_logging.puml.puml
!include ICON_URL/oci_machinelearning.puml.puml
!include ICON_URL/oci_media.puml.puml
!include ICON_URL/oci_mediastreaming.puml.puml
!include ICON_URL/oci_message.puml.puml
!include ICON_URL/oci_mobile.puml.puml
!include ICON_URL/oci_monitoring.puml.puml
!include ICON_URL/oci_onprem.puml.puml
!include ICON_URL/oci_orchestrator.puml.puml
!include ICON_URL/oci_pipeline.puml.puml
!include ICON_URL/oci_policyenforcement.puml.puml
!include ICON_URL/oci_policymanager.puml.puml
!include ICON_URL/oci_queue.puml.puml
!include ICON_URL/oci_sbom.puml.puml
!include ICON_URL/oci_scheduledjob.puml.puml
!include ICON_URL/oci_sdk.puml.puml
!include ICON_URL/oci_securityscanning.puml.puml
!include ICON_URL/oci_serverdesk.puml.puml
!include ICON_URL/oci_serverless.puml.puml
!include ICON_URL/oci_serverrack.puml.puml
!include ICON_URL/oci_service.puml.puml
!include ICON_URL/oci_shell.puml.puml
!include ICON_URL/oci_signature.puml.puml
!include ICON_URL/oci_sourceartifact.puml.puml
!include ICON_URL/oci_storage.puml.puml
!include ICON_URL/oci_supportpersonnel.puml.puml
!include ICON_URL/oci_testing.puml.puml
!include ICON_URL/oci_vm.puml.puml
!include ICON_URL/oci_vnet.puml.puml
!include ICON_URL/oci_web.puml.puml
listsprites
@enduml
