@startuml test
title Icon List
!define ICON_URL https://raw.githubusercontent.com/ThatGerber/plantuml-oci-icons/main/icons
!include ICON_URL/oci_2fa.puml
!include ICON_URL/oci_api.puml
!include ICON_URL/oci_authentication.puml
!include ICON_URL/oci_batch.puml
!include ICON_URL/oci_billing.puml
!include ICON_URL/oci_cdn.puml
!include ICON_URL/oci_cli.puml
!include ICON_URL/oci_cloud.puml
!include ICON_URL/oci_config.puml
!include ICON_URL/oci_configservice.puml
!include ICON_URL/oci_container.puml
!include ICON_URL/oci_containerhost.puml
!include ICON_URL/oci_containerimage.puml
!include ICON_URL/oci_customer.puml
!include ICON_URL/oci_database.puml
!include ICON_URL/oci_debugging.puml
!include ICON_URL/oci_desktop.puml
!include ICON_URL/oci_developer.puml
!include ICON_URL/oci_devices.puml
!include ICON_URL/oci_disk.puml
!include ICON_URL/oci_distribution.puml
!include ICON_URL/oci_docdb.puml
!include ICON_URL/oci_file.puml
!include ICON_URL/oci_firewall.puml
!include ICON_URL/oci_firewallrule.puml
!include ICON_URL/oci_function.puml
!include ICON_URL/oci_git.puml
!include ICON_URL/oci_healthmonitoring.puml
!include ICON_URL/oci_invoice.puml
!include ICON_URL/oci_iot.puml
!include ICON_URL/oci_key.puml
!include ICON_URL/oci_key_vault.puml
!include ICON_URL/oci_laptop.puml
!include ICON_URL/oci_legacymainframe.puml
!include ICON_URL/oci_loadbalancer.puml
!include ICON_URL/oci_logging.puml
!include ICON_URL/oci_machinelearning.puml
!include ICON_URL/oci_media.puml
!include ICON_URL/oci_mediastreaming.puml
!include ICON_URL/oci_message.puml
!include ICON_URL/oci_mobile.puml
!include ICON_URL/oci_monitoring.puml
!include ICON_URL/oci_onprem.puml
!include ICON_URL/oci_orchestrator.puml
!include ICON_URL/oci_pipeline.puml
!include ICON_URL/oci_policyenforcement.puml
!include ICON_URL/oci_policymanager.puml
!include ICON_URL/oci_queue.puml
!include ICON_URL/oci_sbom.puml
!include ICON_URL/oci_scheduledjob.puml
!include ICON_URL/oci_sdk.puml
!include ICON_URL/oci_securityscanning.puml
!include ICON_URL/oci_serverdesk.puml
!include ICON_URL/oci_serverless.puml
!include ICON_URL/oci_serverrack.puml
!include ICON_URL/oci_service.puml
!include ICON_URL/oci_shell.puml
!include ICON_URL/oci_signature.puml
!include ICON_URL/oci_sourceartifact.puml
!include ICON_URL/oci_storage.puml
!include ICON_URL/oci_supportpersonnel.puml
!include ICON_URL/oci_testing.puml
!include ICON_URL/oci_vm.puml
!include ICON_URL/oci_vnet.puml
!include ICON_URL/oci_web.puml
listsprites
@enduml
