sprite $oci_docdb [256x256/16z] {
xTnhSiCs3CJn0n2SlVzf-tvvIkz84AW0MFw_gcNqGrgRJiJWXSPqDL2v6HggP7DhXgoD-M83YPe_bWYT9qBdQTXv8dQUX9stz_rDSWQpO19udWIUfu3dcOAU
fw3dAUXvfe3duL8sspO4llay1JsFwYKYV8q8NoEY5udmDI9yZGXV8yBNw4K-081T-f6Y_FY8NIQNLcjjVi6AMWhqtkvTmcUszHsBhkFtWrqZOwF_F7OCO9CV
v1A-VnWbQ-tppoZ_yYK57zVu9RuM0E1ZT3EW6F_2jRp2BgtM-kQVcVrpUTFSmsTPqO_5XUKblXRnMuX_nlldTd-oJIltpp_YbxX_aFsFWX_Y_fq_iK2b___F
wpyPG87tVt89oxL0_TNsVtnhIFP_E_q8zTlb_R_z_qCFtVylbYtv-Sy-BZa__qNwKVNpFxBy08ZUryrBT5hn_7Z_yFtyRxaM7VBZpBMMVqBFte8YxUSN0ESN
GEVtdy8JECy_h39jFW0HlV00x3p_g3i1N4n1pnFGAut0f0_0m9s4djSSVsK-RV7ekIUugp9q6O4NX8lrtUHLVK6CK-16BRUtXbjPHJk_yu6xMS6TRPUDClRS
AxobaFEim8uvmuqDH9I0xRyR19Vog_FGfUbE0i-JmFCqx3m9F4_3pZCDEq_3pbEXyqJeF1KvpsJal27avecnUQd8fzFfT88u__XrEtw3zW20uuSu7v3bQ_iD
qWCuvr-b1t3Eltvcv_ohJEVllmjFu9n_5Px0EV-gEu5p_bLs0gPx_FMSVtrMP_mv_mhnyw-u_iHEKJm7uTPhHBzD7cw_IbghywzmlKsCGdR-JKIB9xJyjuw7
MuMAJrkonpyWTluLfJRByVS8idgxyw-u_FWJLCw_WdpDJkTVuNZy3MqYnabhWkT-NXCyz_EwuBcVrmJF_RmkTkxdTR5pFw-QdVkTbQ9plxywTEulEuGynp-i
69px_HM04t_QGLZbuqzmTev_xUtuZn_7tw7Z7wut403Dd-xgVluF5sfx_W-N8_zw6psls_b7tExh2etql2xd_-2km_a_F6gzY0mVM2yYeESF_GhmUGfyde2U
fy3dLUQFa6dLv4V-BSvg_25mzEl9lJQO0BtF_XDuVe-eF09oUn8J2Betk4hA3rheqbGAyNdhTN2Xkdo-8Sf__2_uJjOhuM8b-BprKbbV42t-1hwibVDDOSVN
_hOORcOr-NDyNGttivVzc__o8NoDR7mUMmyFskuVqGkpY_vIVVkvVnt22lNVkCcdV_iMkxeX3lFxVlUFRCsxVbpmitBoh_kPZ_h_hRWV3d_I6PZB3wggTFvn
-lpW_XiLz3EZCN--6Kot7y5FVvRpW_YTMIa_DZtz_3BVxmVnFws47yGVKt8_g3_z6CpjvmEeyhJEVEu7yM_EtlTNF_xpYl_uHm7-JZzQ-O-VT_na09B-uuUm
7y3nGzqFNN-90UptexJ_qbhS3tK_alknsmz1FpvJzsCcQbpmnpz0KU0_WAr-AFcnJDqFvFHZWp_r17RxmR9y_X7kvsNoyzsRyQRtQVza0x3G_GykbScFI3yk
byUFK7_-2Mpqusuf_8ZomrEs0JmGm5iFFnwLP01-FvxtOtuyzmy4zPC3yFiDeRtknqC_jlJo0Fn-xEoj0VZV__5EU_rm-_5-3-dh7FviFRj1XxzP8VvV0G
}

