sprite $oci_sourceartifact [256x256/16z] {
xTm5ikCm48JX0rXTS__RRj563zhZo3Xv-hie1i5dfafC7QA3mV-1mOyVFtxy-F7ZnuyVFtxyRIj_t3yqFtxyr_JdlBfg-bUAsug_3ozzK3-oKPL-vo6_b41x
hB-j-zMhQcPy6Rz-fFdHqh1VAoseXZzrocJ4drTLtY-RNNwv5F5x_lN-AEJl1N_mpM3cjmL-LcMMOy_J_WZ9ZOqOzSTlVwyfef3VbptVtrvLHKc_x_qhk_s-
O_x0K-Bud_erUlpxFBykyKT9l-_85VwbgjyrEh3_ltr2h-oFQ1iBGBly_ZXVv_XlpldUByFyvRVyykV_C5qr5ss6-GEtvLSKlFvBTbiNKy20bZws_lN_6iQb
fNw3YFBtVyDh-Qq3NRB0og__N9diw6xfVUBpdvKfItwGydw_02e__ymUskPJhDZUPXRpzyVOleNrCZkMCkz_yEF7Zv_lF_3ZnuyVFtxy-F7ZnuyVF_w7-8GG
FPK_viUF7pz-_FZnuyUF7pz-_FZnuyUF7pz-_FZnuyUlOvdTB_puyUF7Zny_VlpuyUF7Z_-bA-mVvUpoIxFxDRjVcjslsVsQtI_DxjViVhK_vXzNpExNx7vf
Thzczqkp-pMxNvhThzdzcjQFd-sVyz_4Vgv_9_Otxd-dVVuZnTH-dd_ExEVznyH-tdzEx9_w-myfPlOtyVqJVlpuyUF7Zny_VlpuyVF_1_ZnuyUF7pz-_FZn
uyUF7pz-_FZnuyUF7pz-_FZnuyUFlpw_VgPRWlZnuyUF7pz-_FZnuyUF7p_-WVdnuyUF7tywvsPRSkd5_Gos5T_JPRsPA_rjqo-rq_nA-vaqSvdVpE4TX_nl
_fzqMR_EyYk_gBlThrVQXNxV4PayvrVQBvtlLm7_rh7wVBzsR6PnYr_sN9LE3ESVQEL7EybP-Hg_jlrnjb-njc3ZORykyYltzppbpyGQyQVIaAiu7lGhwLdF
KV_oVwWLzKSic_uOytjeCRzMUkRuP_fLm--T7dB0hvvQ_lQsFqxsgyJvJoud-4TRwVFLylSjH6Vxbpx5bBt7BvjcIJhPhzKfZ_dzoU2mNrfdFkPtifRwTT3l
cpNys_rcXEtYk3_VVdmlR_V7XZ-kyVi54FVvpVZShoF-f67JnTJF-m_y-DjM-Fu3Ftxy-F7Znu__iu8VFtxy-F4JyWy
}

