sprite $oci_signature [256x256/16z] {
xDa74S1020110M7d_RkDWHG11mvkftpXL8PJ7b3l5yyddayydwkTZrh-fGr06e0q0Ce2f0567C02b0KMO04MOBpDteBA0FiCw0BiE_ZK9fF_sjR87_m1L7Sz
WVxlma3-3q0ad-8cc1-0r4jlugikuldxnXFF9vvFlLyblon06e0q06c0qGOW3K0QGBkVD01XWEqd3Q3TJnh0tTwT7J4EX40O3a3gwloptUSzjOL-cseO0X1y
p6XyOypFLt3xut41_kGd7Qf4IzekFb-Aoj71Dr06P6_Xa_usSRqQsz2v3BWxbX_Q082yWm_v0NeBd_43zXu-uWVi3NpC3-2RdlR-dO3eR_V5Exw0F7O0_wqV
qBVpw_vRVuxBpNp2Nq_Z97xT3-Zx_7xjf_JzV1y-utS8_ohu1_7bWZ-3RuIlGXQdydtu1Nyol-xFv-iJ_2k0Ft_vARu6yu7bJ-RFNNvzQVSxcJ_N3_0FFzH_
-2M_flZrlUNtE7w-lvElNNmFu-VxHVhD-kVpDUhc1_mPVC0_a1_dLyb_5_Y0F-3i2_ERv2Vw3V2Z_SRueNv3Pr-ityZD7-mtm8_sso_vTxhV_DcN_z7N1V1Z
_0QE_cY_WRClUpmsmC_O07zB2Pnz2HlW7oaB_BZPaIgCRGRvLcy37b8MRlwi1ZobBF2JfeS-vopS_3aDAEG4-FXceZ8ty84BWdc1zUByQfXU2F0RHkY2MG5-
oBy5rX9-VxhBT_dI1V0RfWY32Na-F_2W9nrKNV-y2u4D21YbpENg7Mtc_anNeIQkBBa_Jw4Wi33rP-aubi2SxrDm_5e3rCkt7vuhjNI0vpzV9c-gE7PbWD_G
0V2wDNxlJN2nLurhG00Vw030p-a0pv_w_o8Ay5UAJkLZTUVkVgRoR3vG_Gn-7O2Di4hjm9Iph-gOi_jhab7y2cOs_vcJnUUV5ayv-_WlJLwZ-S-05NmjvwlC
FtpbyxM6Bx7-my_NIolu4i-_9l1LvYj9ltZtQpLVg_dtRhu0Vgw_PhY6yAi6W1-XNyttQBu-obUyVZNVVkSFrw_cNxFvxsfNklzTvVSuFlybZrZzQhvNyxsQ
RuolG7xG5_ix9o2Cv7irtwlv5ynN5jzh-7vTx7A-dSn7Qitbcwarra-L6ig_iKf7x7wWbV7yUiJn3LUQnZTTQPYVBpHy-VaJ9SPlA7Bv_6KzsY__9QByTRwU
6k3P_gS6ECV_YRdj7kAlRV8eljwyt75gK6_vRFTBwNw_z6kxN-ly-YMs-xNTBsttQv5V6j00tA_5_hF-zYR_wYS0YBu_8FzjX_k5llYRxu_Iymv07_qM2A2F
RW2WZsv0Afv_6oi_-7aqGqSPNbEtYFu_F3C0V7W0-F00xEb1sFDZbll4YHCdJfmuSUB4YHCdVW
}

