sprite $oci_service [256x256/16z] {
xTq7RiCw60JX0rYBkVzfNwyHyPjqeB3i3afwh4-TSkFdIqbVS_VBd2_57xynNue_VcE-NkP-dMhzrB__F6dArES_OAMucZOrAdxf2Bwa4Vy1kuM6i-2Nlt7E
NhxGLxzn2F_ppFcIELzozykSByKVV_oRvCsF7sz-_7ZpuyUSJpVhK3yZf0FvZ8dEypFeCUV3PU6do63x_-HlRFYWLjS1-7v_knFmqaD_l3w-Nw2gZV7z_hh3
-Q1txScF7uwT0V777tzL_7GNVr7yyMV_5t_yyJkE_-BFzOzS_rgtH_riaTtrxtx6ntpd-__aSl-lnGD0JFZZ79duso39mE_q-2T9lIYln_-DPywNuhVcI_5R
ywNuhVbI_DRy-7VAsXz_Zl-OypF-e-buBptu0b3dPR43-0t82phzS0OVceQhPoi_WWzDGeyVJk13Gz3fXqlInNaLV8_YZz-O3_77Rym7Rt_yhCrFAQMKKaef
fPHIIYcbz-ziTq7n89VM7_Fr1-YVLhXwtDOElULRow-RlubTnzyoTVfL-47ribx4hrk5lqBK_kuvEf__BV_z1m1e6pz3VlNvjQo_cjngLjsTwlB3fJzwhV3G
iFj6Ik6ldQBzESrj11RnDwQXnyzxQ7MCO2d_RVfkbVvwdrSu5ppyzVhRFr3fPmE_QdzxWh_whttyw6j3_c8bMjXVJyM0dx_QsW-V-Yd6Dfli_-2s3dUV_r3u
Tpd-KOrS-fTMwxlrePFrpl_wHhh09_urnx_IyFYtVT8uvAzlPtq_rHwGXf-D_7Juxrl0LVlflftbn__KAm1jFxstC_lWt-T7VzVhXxjolh-1wV0tlPM_yJU5
twYKKaeffPHIIaa3UVB33pzyXV_DMx3Zgyo8_tphyVMZcVEr65zQsw-XrkTh9RucPC2VvDz1BvdpjGPVqpBdQu5zdsPcpjTilYPdpjTK_gNfpUHhWURnB-tX
rpD-hT4a_akBD8UlPPh1VsaN_-i9_WJAfsceoGj_2xwUQp9Va_bQdwz7C-ThSRwUpfolbVdwWIRo3_FBsZ_EFye_pZ_AFyu_oZ_EFyj_dNV1O_uyZz-SZpaV
SpxcVCpvUFFZD-TZpiUSZpaVSpxU_FZD-PZpCUTZpiUSZpS_VdC-vdpC-PZpCUTZpez_x_3su-rdDJ_RzG3Uqm_6_WkC_O2n7upzWB4VZFqN6Fi1N_y5ndx0
s0_6_XUdzIi
}

