!define OCI_BATCH(_color)                                 SPRITE_PUT(          OCI_BATCH          oci_batch, _color)
!define OCI_BATCH(_color, _scale)                         SPRITE_PUT(          OCI_BATCH          oci_batch, _color, _scale)
!define OCI_BATCH(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_BATCH,         oci_batch, _color, _scale)
!define OCI_BATCH(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_BATCH,         oci_batch, _color, _scale, _shape)
!define OCI_BATCH(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_BATCH, _label, oci_batch, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_BATCH>> White
