sprite $oci_function [64x64/16] {
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDC988ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDD6000007DDDDDD95DDDDDDDDDDDDDDDDD97DDDDDDDDDDDA
DDDDDDDDDDDDDDDDD7000000BDDDD92009DDDDDDDDDDDDDDD9006DDDDDDDDDDA
DDDDDDDDDDDDDDDDC0000021DDDC400003DDDDDDDDDDDDDDA00007DDDDDDDDDA
DDDDDDDDDDDDDDDD80001CDDDDB2000017DDDDDDDDDDDDDDD40000ADDDDDDDDA
DDDDDDDDDDDDDDC000000119DC200005CDB2222BDD51112BDC10003DDDDDDDDA
DDDDDDDDDDDDDD800000000BD400007DDDD20006D600009DDD80000BDDDDDDDA
DDDDDDDDDDDDDD400000001DA00006DDDDD80001800008DDDDC00008DDDDDDDA
DDDDDDDDDDDDDD720001668D30003DDDDDDD100000007DDDDDD30006DDDDDDDA
DDDDDDDDDDDDDDD30004DDDC0000ADDDDDDD60000006DDDDDDD40006DDDDDDDA
DDDDDDDDDDDDDDC00008DDD90001DDDDDDDDC000005DDDDDDDD30007DDDDDDDA
DDDDDDDDDDDDDD90000CDDD70004DDDDDDDDA00000DDDDDDDDC00009DDDDDDDA
DDDDDDDDDDDDDD60002DDDD60004DDDDDDDB1000009DDDDDDD80000CDDDDDDDA
DDDDDDDDDDDDDD20006DDDD70003DDDDDDB10000003DDDDDDC10004DDDDDDDDA
DDDDDDDDDDDDDC00009DDDD90000CDDDDC200030000BDDDDD30000BDDDDDDDDA
DDDDDDDDDDDDD90000CDDDDC00007DDDC20002C30006DDDC400006DDDDDDDDDA
DDDDDDDDDDDDD50003DDDDDD50001CDC30001BD70000CDA200004DDDDDDDDDDA
DDDDDDDDDDDDD20007DDDDDDC10002CA7777ADDC7777B4000004CDDDDDDDDDDA
DDDDDDDDDDDDB0000ADDDDDDD90001BDDDDDDDDDDDDDD300007DDDDDDDDDDDDA
DDDDDDDDDDDD80001DDDDDDDDD801BDDDDDDDDDDDDDDD9005BDDDDDDDDDDDDDA
DDDDDDDDDDDD50004DDDDDDDDDD9BDDDDDDDDDDDDDDDDD7CDDDDDDDDDDDDDDDA
DDDDDDDDDCDB10008DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDD1100000CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDB0000008DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDD8000018DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDCAABDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8
}

!define OCI_FUNCTION(_color)                                 SPRITE_PUT(          OCI_FUNCTION          oci_function, _color)
!define OCI_FUNCTION(_color, _scale)                         SPRITE_PUT(          OCI_FUNCTION          oci_function, _color, _scale)
!define OCI_FUNCTION(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_FUNCTION,         oci_function, _color, _scale)
!define OCI_FUNCTION(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_FUNCTION,         oci_function, _color, _scale, _shape)
!define OCI_FUNCTION(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_FUNCTION, _label, oci_function, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_FUNCTION>> White
