sprite $oci_iot [256x256/16z] {
xTrNTkOy38FX1LWuslzg_rw7qqATru4DuZuK7gRPJlds9qP_PGT6NoHDNnFEbzBqDU5yAPmlcVMa-JL-xwD7-nkZLN9n_1for-s27F_cize5R_IZHwtzlS2r
biW5d4FeMYBzvn2m5-y_Xm35FFrgbWDgCUT0Vldx-n0b-TKiv-xlGwvmFr3DsQ_N-cNW7pzm_OFwbUPNxwqKxH__uijjP_z-gNy3VkkRpFqv_WqVCFv5-Xr_
_jMKM2vWt-NlVzwSX-Lt6HUsW1fuDF40Z6-vR-KRBU1-_dNabws_0G0M0FXfFhy0td_ro_CBuFshKHrO0EpdYtVcy7wojSUZO0j-dVUTsRZ_dB_FJs0Mm0sh
Co_iamlmm_Nu4tW_pmVE0FmK7pW5y5Dyu1p0J_61am0_nGVE0lmKltlQ0lmy7pWFy_Dyu4J0J_61Cm4_nGTE1VmK7pWNzlDy_hk0Ic0-lu0By0DyS0607-2R
VWJmV7u19q-i0JuNu380u1ile0vY-VuBCEBtcnnCuldy0av-Sadp-GMSZOBv_08EHm5yF409W0ycarzRhIH-xNL5yMkpdw_-0dxj1bmayNm--dO0lgEUse0_
VqcYDs3-pgSty5Hzd_0IVX_n8dxpml4z_AR4dmylu4tyrit3o_W0nu0VkO1BsGjGDokRBtrrJf1VtveHmjTt9aJuzRst3-1hDowHh28qzlobx0M8JhfVwNw5
ywLi__YLxh_2_Hg_PovbBq3H_l6l-G0O__Z7F_xnuydpryJfQzBqDMdwcZHzJJXV2kTBuNmfd2yzWV-zvmJ7qxtvl5_UVDwlyJlpUR-y-TLV9-dikyep_BNi
0_qwzTTfvtuzn5-RFislGt_vfm_5tyjJ_5-OnxyUvL-7_bs_w5M_yG9qu1__-5VzcXVbr_Z_6RC1Fy_tlFwJbfEVl_wlyVVNeWhqbql_5_XZ7eHdyiS__l6F
V_mxcJ_-yUzi_lXtDd_yEvo_byoozhq9U_VNXF5hlFZH2vZV_qrUmFp-V_82vkz_SZUmvk__JBBYz3NljKycaybaCfbC92NNGIz3_TkW5-B-PPpkHHn-_SNc
flj6Fd0qqCBsXTylVP7BwHKn-PDLmjRW-O0VA8Bn0JzG1UC3Vg0CnWVyG1sC3_Y1GXWVy0ELC3xW1qfXVC0FrCBuW1yeXl41Fr0DumD-e1p6v_nyFNu-x-S_
Ew7rqjDKspUdDVYWdwyiW0_ueTO2-80VA0xm0JzG7U1pVg0ym4VzG7s0Z_e10C_d_HlmKqLz5d0_7rni_uKKFu_F3wynuAFZ-twURxc0nkSDqkuclfelOFbM
lm1_hzsh_PzsHCrB_NBsmsUCV_nx_3vV_uqFwRpP-BUxV_oxUSJuqMB-5vb9VeDRCx-RJBpNHldd4BGNxp-7eBLu_pc4RRKNx3-70AMmRx88P26TU7zDT_gj
lqb87dQrXrDwuFat1W7Q07u00WVc-oUCNvF6hmdJrwJnQue-C0xsNm4
}

