sprite $oci_web [256x256/16z] {
xTtHbTmW38NX0k0UzTzj6bWFYd-1mEY-9GbQVMAony6p7ij8HOFV-78aIOxV_6ZqxDST_6U_xk0_-zMkq4kEFpawVpBQQ_zPOtbYoE5_NjdiZ3mZnlx1Mji-
0yB0xrXjE-UNG0w_Q_c-U2T_x9UZ_6RfVlx0xobXcsNKl9n-_motqZluNh-_ogPw6VJxovp5z_lzXImXu7NhzlihvUhVyXr-F81yVhpVb3S1i6KEFwisFxXX
lt__0VZxbTSF1z3tuAVv9PiNq2prvmy0e4p0Zulcy-Fz-GDGo4w9b6rwp9PylvyNxflmkPzNvc6x1FoaT8fUDjcVFm05xf5c5y_d0pyjtsr6pl7Rf83-W7-Z
gy03_Csc9eWli23v861dlwq8u0E_DZeCJ_6tdMu7KRxWalmReWrOmjTOIhBz1lGJt-hJ0lp-xm2JWJP8UqK9M-JO8CJthC_my_xz4i0dVZw0xbZaacpfv-tx
8O0VwjUxFh1VEit_ObdSvUKSFsZW5HyMYVJZhmpUpeZ6YFqjfdC5DMxlyiPFljB45w-Xj95__kqfVjIxQnJMjWOvJHz_3NC6VlubJ7xY6zP90uZlLr_rwtQ_
GBKB_0VnUS_njQHLseb-4RyazGKR3PgEypTmu0BiS02Sx-yXNixzckT_29TFy7E-s2rVraO7VS_T_lsNC_xvVfK_W2-oblj5bkTkV_vwnZ_VhtX_M-tlU_d5
_Bn0ntxS_a45oa_uv_iLxDTwlyeFAb3-kVxurULNXb-9WlFz-fpVrldjQtxTvrUSl-Nusov-vVWLvjUD_dwsdzS02x_aBt-_qz_p_lbpVqGZLlxobr-7-daH
kFtbBt_vbUSNzvTVz_hr2N_vor_-yfVVLlZjE_xobryt-sNVJwLIgLGgbKgbKgbKAfKw_oX_-Sl_YViVlUv_-LF-yfU__7Qcl_pbx_N-r_AN7_Wl_lcFyjl1
_lANlr7_pJ__M_wxdtzG_g3dVvI_7_xybth-ZvM_ddzsbB_yFSnVptyiVx_h-RUgv__MyvzV5YX_FVzTwNwq_lBFlsYN--tltEslp__f473Aylhygm1__w3V
RlZ_fsNvpPqqlqtmTtkTFi5ljkm5O33-mjhj0s0jF4kstwnZ_w6VVynhDO-THshr0UYlEYv_Ghdo7yOt-we_kA9jamo_xPNOZi_2n_VS4lGySNwRfXzTmZT3
2MixLZ-k4pRdgBw3zEjF3zeqFoX0Jp1YMcTLe1tuyG6Q6Hu0i4C_xwBRcpImzv5-sWR_LcfsYf-tpq-qvldRgnSml9pejet_LVz6uZalDgSbtZ_6hJYFRQly
R7lZGsv71CwiP-aN-mST9EZ10A97PYlJfFL-6oonPN7q5k_tT96Wp_HdJ01qX_pkHXBqEVw40O3-t7vUFa6Vxu-V0EqG-6dnliNnUfmVz1AP3lQ8-pcV9swJ
MEL5V42AzEVoUPz-F-St2mvfr2Bye8Nq0SJxEPydOgj0pGG-Q1RumKX1q9L0k1_mfuPkruHwcmu0-0b_Vj0F5eSMQvQIhZy2_A1MKjut7LWfDQv-F7vGA3Nz
NTz1SxGDqiTDjH0_qCyDQjrlozFpzqev_VuIjbdWvlqdtpOCshx_ujkk-Na2pMvck_Jv6H1SVaVTdJD0FFXTV3ia__yYTl3jfBpsDqUrSpFssxSpy3VxUdxw
xOByyDiLUVJR9Ub_-IqZbNy
}

