!define OCI_CONFIG(_color)                                 SPRITE_PUT(          OCI_CONFIG          oci_config, _color)
!define OCI_CONFIG(_color, _scale)                         SPRITE_PUT(          OCI_CONFIG          oci_config, _color, _scale)
!define OCI_CONFIG(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_CONFIG,         oci_config, _color, _scale)
!define OCI_CONFIG(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_CONFIG,         oci_config, _color, _scale, _shape)
!define OCI_CONFIG(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_CONFIG, _label, oci_config, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_CONFIG>> White
