sprite $oci_2fa [256x256/16z] {
xTi7agj038JX0p1TVV_JlXn5MNXOs2caloiwDVx8qK-DBecVxyUF7pz-_FZnkxVVzWjN1pz-MLNzhF_muyUF7pz-_FZF4_3ZnuyVFtxy-F7ZnuyVFtxy-F7Z
nuyVFtxy-F7VX-Zgrz-CTdxjqiYl5-dWLvvHsg-tKjIlYLJpQpwZZ5-dKy2l3-RXVdqu5VtuyUF7Zny_VlpuyUF7RxVpHsexVvGsy--XJVt-avP-z_L7VZD_
v3VpHtupV-GtyqT-Ct_aD_D7VWU_dV1h-YCduLVtlnwy6lX7U3lXL_D7Ri8lwe_Wo2_l3-I4Nyf_h55rVyvH0t_YKGD_0b83Vo9I0tz2KWD_Oj9g_zstRERV
Eb4uz7RE-tM1FwywoxTg-6LR5VrwjyfguRUqgcsz7__wiZpN-tNVnXI_7k3VBglpS_nvvsB-ShyNrAppwwxdtxJ0lse431VoprTkT_Dp_-eHOE-pFTjlt_Fp
l6M5VrvmFVzFpUN--ms-qhzTDAm5jmDTSwLXiJ_cM5_RxrFyGdvxMb_CxslvkL-B_7acz2NzrYwtD4eB_NckhjTKrlljKDxERuVgTdvRsjpO7uD__HO5Ftxy
-F7ZnuyVFtxy-F7ZnuyVFtxy-F7Znu__k6TBUkDtHmb_R1bl-rN47pkw-OT23dhr9pNywktNf3-yLMVwExyTQLJr-y-lzlwZ0PRP_lbxHZD_J3R_L_P7_iGz
keNycl3RXVoHd_n7HRyA-2F_s6_RHVnn7tXshsZKElxph5yFzUTyxxlA-hVmo-ZF-LAvuny5F_wCBxNnXpUR-RVTUxtyUkLNAx_lydFz0pz-_FZnuyUF7pz-
_FZnuyUF7pz-_FZnuyUF7p_-0gdknuyVFtxy-F7ZnuyVFtxy-F7Znw_cVAavNshEbvhpfUPygJbVpVbISxxKd2yrvqlD-PAFCzHx1AXsUlFZ2C1F2254ZV9f
VlpuyUF7Zny_VX_by_tuyUF_2W
}

