sprite $oci_vnet [64x64/16] {
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDC87DDDDDDDDDDDDDDDDDDDDDD4ADDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDB6104DDDDDDDDDDDDDDDDDDDDDD0027CDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDC8300004DDDDDDDDDDDDDDDDDDDDDD0000049DDDDDDDDDDDDA
DDDDDDDDDDDDB610000004DDDDDDDDDDDDDDDDDDDDDD000000027CDDDDDDDDDA
DDDDDDDDDDA2000000027BDD98889DB8888DC8888BDD95100000004DDDDDDDDA
DDDDDDDDDD80000026BDDDDD40003D80000CB00009DDDDDA6100000DDDDDDDDA
DDDDDDDDDD800019DDDDDDDD40003D80000CB00009DDDDDDDC60000DDDDDDDDA
DDDDDDDDDD80000026BDDDDD40003D80000CB00009DDDDDA5000000DDDDDDDDA
DDDDDDDDDDA3000000026BDD50004D80000CB0000ADD95000000005DDDDDDDDA
DDDDDDDDDDDDB610000004DDDDDDDDDDDDDDDDDDDDDD000000027CDDDDDDDDDA
DDDDDDDDDDDDDDC8300004DDDDDDDDDDDDDDDDDDDDDD0000049DDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDB6104DDDDDDDDDDDDDDDDDDDDDD0027CDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDC87DDDDDDDDDDDDDDDDDDDDDD5ADDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDD72BD82A23CC1761111822227DDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDA06D31D005C0750666951158DDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDD21B07D00060750557DD32DDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDD8030CD04300750557DD32DDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDC004DD05C10750666CD32DDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDD509DD36DA2872222CD44DDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8
}

!define OCI_VNET(_color)                                 SPRITE_PUT(          OCI_VNET          oci_vnet, _color)
!define OCI_VNET(_color, _scale)                         SPRITE_PUT(          OCI_VNET          oci_vnet, _color, _scale)
!define OCI_VNET(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_VNET,         oci_vnet, _color, _scale)
!define OCI_VNET(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_VNET,         oci_vnet, _color, _scale, _shape)
!define OCI_VNET(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_VNET, _label, oci_vnet, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_VNET>> White
