sprite $oci_storage [256x256/16z] {
xC450G0m302W0fV-RHTZ1ln5003W5WK0000000000000003mrmC0023QkG_Snc4W2g07a0pT_xQBicaSVKgkOoJlfn8SbkVUVrzy7WW_Fpy_Fpy_Fpy_Fpy_
Fpy_Fpy_Fpy_Fpy_Fpy_F_ymnspEkc3SH5mWRtwPU9xkBzKJ_neEao7HdxVUugyJh5D_cZkK3ztpdJVvQtdsnyb3_U5Pfj-_VXOT-_FiytMtwEy__GzhXxwF
TYNlL5P_liIe2uTDFzsV-u9hy6V2khEPiBSc_tREdzlP_z7y-DFjpzV0DKT7sRt-Iui_Zt-4FxVgXSSfpsly7xdFdoydXgBzsnGD_ZB37VwF1FvR-VCSZ_7d
ebv_paFzfIZycwvAEkx_Lk5USmsRZlmnowxopVsvUpXeZlrRdglh-k-aVzdYnNo07TwJxFLdHMf_Lg-V_yxzSKUbqUDVPlNdxhFcgxRvMQQcv_vVBg_ZKt4m
ftkG0Thx-4_GdYW-xrydT_Kl3VvmtP_y-S6CofgSWC9zZoP__-FN7l_lzFFpy_Fpy_Fpy_Fpy_Fpy_FpyszF2Jy_Fpy_Fpy_Fpy_Fp-_-__y_Fpy_Fpy_Fpy
_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpl5dv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vlu_714H4H6HVm
}

