sprite $oci_authentication [256x256/16z] {
xTs7UUim40JX0i3zflzgNyxXB9YaeCFkD03y9qT6dbfAQUYV7HWarR5nXnwB7TDK3lew2toTWxxEMo_9d2_9GLzdpfSSz7NcVCb1NsVEbypvaZbVCkTBvdp9
d2-PyoLplcJEbypvaZbVYj-QBvdpfVYj-P8vNuhVcY-v-uStN-9rEkGz07dxXxbVYuhVcYzv--ENEJ_-zGrv3q2-_lZZr-BYZp_--4tvKlpnnnz__F777t_y
ySSVV_pnnnz__F777t_yj-JBZp_--0zpFyxy-EF7cHz__3ZpuuyVRtxyUFFZnviVFzxy-5d0T_OVU0-0rykR7p_cV33dWpaVWrzzUVvfcJaVpFbWpWTpFfZp
mPmFvdpGzHs0yGJebZaVpFc0jnumvmFUUW1lFO2t7i1R3s2XhxF0rrdWwrGtS6YpppsbbEx-ITReuWykRpIx-fDhwtVtKxzLvbFPWcKMu8kUjOus_bzcwA4M
wkiQB3ITfbgpKFzZEPflfRxkIUjiSZ1Nxs-nlcxv8kkVTJ5EsDSEG1VMy7InEkMjbsJEbypvql3cIpBdI-PyEVC7-F81NpxuyWVuyW5VFlZo1_Zo0MpzOCm7
NpxWomTy_H1--8x-yESH5luQuCRNFzg2hrERtz-ljshErnNRtjAlgRhoTTs6T_5VFitHo7_BG6tzySSVFzx--0zpF-v-lFtnu-sF7tS_E_hXSV-ndn_WOJ_R
-MTlKz_CpxSUzhELdnyzx6SZFxR-cY-gTl3NV56sWR_cYxh-_felgEllvqU73FrdBmjeveUIF--dbH-WvC_xQUG7W98_xwUDds-L_7a_JVpygEJF-sdXvvVA
NtppVffz_b3ov_syjh_6w08_7VoQtpcFry2lMnyTry2lsKqpKmE_9hVCL0tycZkAprmD_1eJV35P0xzqwtCZ6_W5m74B7vRw9mQWc_mqy8j3j_bfuDUDV62J
0V3kjl1pfjVmenFXFG3ErjlF-Lx1pq8_z1q05xNUprLyem5mPSlzBEK3pGR0zNKQ0BUqriy2_geH7FmhbuT6dLkRknkBz02xFppezCeygnLuWECM_VeHNB6i
oVlFL-lN7w9SmQzRVNYILsZPeIbUgsV_Muvftdg0j_Nf8m
}

