!define OCI_CONTAINER(_color)                                 SPRITE_PUT(          OCI_CONTAINER          oci_container, _color)
!define OCI_CONTAINER(_color, _scale)                         SPRITE_PUT(          OCI_CONTAINER          oci_container, _color, _scale)
!define OCI_CONTAINER(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_CONTAINER,         oci_container, _color, _scale)
!define OCI_CONTAINER(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_CONTAINER,         oci_container, _color, _scale, _shape)
!define OCI_CONTAINER(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_CONTAINER, _label, oci_container, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_CONTAINER>> White
