sprite $oci_healthmonitoring [256x256/16z] {
xTrfSgK-34Nn1S2jk__L_iSUNhbubkEq4riwvoj2rAyde3EvUAeM4H4H4H4H4P5JXny_VlpuyUF7Zny_VlpuyUF7Zn__Tk77Zn-_LDYFNvAEyQksNrh2rtMC
NqlyEiElF--_Y_lrenFypQPgVYtm2_-FjlS7gwRIANxyMk3NQtlxzHB-1NnfPx_mBtYPECQlh_1hM_-rmgzp_6gwQlcNFKstxUZ7ho_ptwVujOGlxUXNRR-M
-FMcK_ogujSIl_2_QJF_qWUA_Vsp2pMzLXdyqU5J_BCR9Ts5_T7XVlluzHc_ZlVFhWoE2t-_JVmAYdt9_R5lRgssy6jof_3t9dI8NoF5vytj_Nw_5lcVbcJo
g-rClnxoo5QfBUG7U_VnEzwg6RztyCVyIRzczjuB_VCVcWZNwh7kSGTxT_7xt-Ryjt_qzjYt-ZNIrBzkxL2mDsn3luOsXVyuxEuVkhr5vmTxj_NZxynUOtlw
V7jh_z3ptQrkwVtgr-7lxlU8NnFvfNtzTp0zxVSPVe_ubTRl6V-4vX2_7oVkj7uF-VLvlu_rp_Ftzm_DFwsm-jr7-8VdOt-yEPFVzkR--JHGDEUPpl4RVtVG
9_kjgFuWVkVsDvFb_D6e3_TRtOo_E-hS_cOsez_g5CtUkVtXh6lvs-4xWz_pRunExR-A-yDfv_1RZmNJ-9tQ7undybiFXUDExJV-_hmJ-VtHIrJtNt9glyDo
-Ot_DHVputUplwuVlolwZVz7hkZ7xsPvIJz-5_NZjoIviX-_A_jTtN-vjj_d-F7ZnuyVFtxy-F7ZnuyVFtxy-F7Znu-_EMNyEvYr5nh-Sj372-f4FtxLz0l_
pohwLSZljd6_a_fllTRnFnr8u5S-Vzj7llddbBzjVtyBlOlxVq_Kygkkl-LKzRSby0_V__HGfVk_dihhRzUgus-hux-B-rN5trwWgF_Xz19-uM_tx-dF4Nxy
-F7ZnuyVFtxy-F7ZnuyVFtxy-8c8Y8Y8YCXwpDOtznNlVy4FhaZkZxznVnM_trquit_eEzVNyxk8tuNz-F4B_--k0lS_xlyy__7yt-G2xt_58Y8Y8YAYlm4
}

