sprite $oci_sbom [256x256/16z] {
vCyt5O10040n1NddtoqpVQB-ECWuvKvZmNZKyt_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_r
l_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_qtjs0Lomq0G1C07s5lt_zU6OzA8mkkq2cyEMoory__Ani_F
py_Fpy_Fpy_Fpy_FttZxftv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-_fjkSRpRwX25
e85_sdTnp9Y7e8a_zLuOT2OFvHx-s7r-rBMykxyM_UiLnrEnX_yQSQK9BSPouLGSpVmnlIgarb4yxjCV6y_vHpV_MFE7EEsQr_9evA_OSGHpz9-I2RsQ-6FV
FEHnXx_gZjv_vkyLj_xgvw_QyFwpzVolmobgu4yJhzx_i_-6tS2V9izhdoAN7erj_RNRFsRyrSa_Llr1kVHcEAgJ__P2FyJh_-I_AcH_TVAVkXq3RTE7ONF_
Px__c_jhVEx_Jtj_LUYxE6J8E_e_izRGtF__rdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-
Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vlv7
}

