sprite $oci_sdk [256x256/16z] {
xTb7bkD830JG0nJZyVwtdTMqGwN8jX2HFrRomYT0VzwAv5dXv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V_xLe-g-wedopF7kt_
gB-IyjD5NFZFzDT25YyMSk7Fy2-gA_x2Vvg_YZuMy_zfpu-oSNYm_-MhTRqexH_jJ_4N_e3vN_jhrvVy9_g_vBw_yATi_nV-_E0_n_YhQJD_HTttdmFyjPhS
znzZ_4cEjVzS-Cz9_kfS-x--jeF_nV7VEM7_TvJL_CRnRuRu5xYIYUU_QsXzTUK_1_J_-ln_yFMVd9VNluPU_wl5B8w7NljFrx_lXv-Vdv-Vdv-Vdv-Vdv-V
dv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V_vZc5n4H4H4H4P7ypRJ-QJ-_yM_v-_cDVypVps_zQ_v-_dil0FwZjOB-1P2z_OVblxF_iFtTsNyu_jhP
VpZ_uXz-_UN3zQUUzh_z06GFVthQ__O3a5tywMZ_smz0zl6dlVtbfVPnJAy_3GKrjh_wqrpHNluqB-pgxns0xEPFR_khltK0ify_hUsl_iu1o8x-TBQ_-Xi7
87lwqzZ-wkyRWEpgJr_xgxzj0BAlFstjh_wk0SZE_dIrl_gR1Y1x-tF-o-IEF-VCyEUUF_oJ-TV-y4_cN_l3Fvb_xG__PFwrF_oJ-TV-y4_cN_l3trxpb1lm
UMS_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fp__Vm
}

