sprite $oci_vnet [256x256/16z] {
xTe74jiW443H0qWxtF-qwScE5J9I6elXlIdkvRkeGRm00000000000000000000000000A35z5fhXKzUN_-_-p-PE7v4_oTprW_eJzF53-fFCzKFxK-Jn0_l
J_NrHVsfDBwmFrNLb_UdclZw_bHKNz-VQkBh-rDHVNr_YbZlzLDxOCdwwhVHxXqnIhitoQAdNVtP3VMBmWSlDgO_pT8VQKn_Eihx8utiJsTXVwI2_bJI7wci
FmtkZrJRdqRsntpzet__K_MV9Sk_MVeBrt_r_Ljl_zZ-7TDl_oVQlG7zbGUXsWC3-jkzPG-0dUs1hOz_nlytSV_MunynqdJzMuz_Her9-gDEVNzKA-tVUlvJ
pAEWV-lvZp6XSrX_p6f4VqpjVBVvxm0000000000043xedl5vPQys7xIlRAzPVyrS-7-VkKrSyF-uoLpxVxezCTk_HdPwM_z_lidUzF-FF_Ty_xZ_VepvzgV
zkZFfT-rlwtSVosBs_wh5VfRlpzlNRq_YtlzRT7-33gx_PcxUd_BfTzBV_OkkVpBekF13j-g_QdN7_lqnvRzSTCVb_whPVgFN_J7kltNldv_xDuVE_J7bltF
0G00000000000000000007m4
}

