sprite $oci_monitoring [64x64/16] {
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC00
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD900
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD500
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD100
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD9000
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD5000
DDDDDDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD1000
DDDDDDDDDDDDDDDDDDDDDDDDDD6DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA0000
DDDDDDDDDDDDDDDDDDDDDDDDDB1DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD60003
DDDDDDDDDDDDDDDDDDDDDDDDD70CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD20007
DDDDDDDDDDDDDDDDDDDDDDDDD409DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDB0000B
DDDDDDDDDDDDDDDDDDDDDDDDD105DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD60002D
DDDDDDDDDDDDDDDDDDDDDDDDA002DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD20007D
DDDDDDDDDDDDDDDDDDDDDDDD7000CDDDDDDDDDDDDDDDDDDDDDDDDDDDDB0000BD
DDDDDDDDDDDDDDDDDDDDDDDD3000ADDDDDDDDDDDDDDDDDDDDDDDDDDDD70002DD
DDDDDDDDDDDDDDDDDDDDDDDD00006DDDDDDDDDDDDDDDDDDDDDDDDDDDD30006DD
DDDDDDDDDDDDDDDDDDDDDDDA00003DDDDDDDDDDDDDDDDDDDDDDDDDDDC0000ADD
DDDDDDDDDDDDDDDDDDDDDDD600000DDDDDDDDDDDDDDDDDDDDDDDDDDD80001DDD
DDDDDDDDDDDDDDDDDDDDDDD300000BDDDDDDDDDDDDDDDDDDDDDDDDDD30005DDD
DDDDDDDDDDDDDDDDDDDDDDC0000008DDDDDDDDDDDDDDDDDDDDDDDDDC0000ADDD
DDDDDDDDDDDDDDDDDDDDDD90000004DDDDDDDDDDDDDDDDDDDDDDDDD80001DDDD
DDDDDDDDDDDDDDDDDDDDDD50000001DDDDDDDDDDDDDDDDDDDDDDDDD40005DDDD
DDDDDDDDDDDDDDDDDDDDDD20000000CDDDDDDDDDDDDDDDDDDDDDDDC00009DDDD
DDDDDDDDDDDDDDDDDDDDDC000010009DDDDDDDDDDDDDDDDDDDDDDD90000CDDDD
DDDDDDDDDDDDDDDDDDDDD8000240006DDDDDDDDDDDDDDDDDDDDDDD50004DDDDD
DDDDDDDDDDDDDDDDDDDDD5000570002DDDDDDDDDDDDDDDDDDDDDDD10008DDDDD
DDDDDDDDDDDDCDDDDDDDD10009B0000CDDDDDDDDDDDDDDDDDDDDD90000CDDDDD
DDDDDDDDDDDB5DDDDDDDB0000CD1000ADDDDDDDDDDDDDDDDDDDDD50003DDDDDD
DDDDDDDDDDD60CDDDDDD80002DD30007DDDDDDDDDDDDDDDDDDDDD10008DDDDDD
DDDDDDDDDDD106DDDDDD40006DD60003DDDDDDDDDDDDDDDDDDDDA0000CDDDDDD
DDDDDDDDDD9001DDDDDD10009DDA0000DDDDDDDDDDDDDDDDDDDD60003DDDDDDD
DDDDDDDDDD30008DDDDB0000CDDC0000BDDDDDDDDDDDDDDDDDDD20007DDDDDDD
DDDDDDDDDB00003DDDD70003DDDD20008DDDDDDDDDDDDDDDDDDB0000BDDDDDDD
DDDDDDDDD600000ADDD40006DDDD50005DDDDDDDDBDDDDDDDDD60002DDDDDDDD
DDDDDDDDD1000005DDD0000ADDDD90001DDDDDDDD29DDDDDDDD20006DDDDDDDD
DDDDDDDD80000000CDA0000DDDDDC0000CDDDDDD702DDDDDDDB0000BDDDDDDDD
DDDDDDDD300000007D60003DDDDDD10009DDDDDC0008DDDDDD70001DDDDDDDDD
DDDDDDDB000030001D30007DDDDDD40006DDDDD40001CDDDDD30006DDDDDDDDD
DDDDDDD60002B000080000ADDDDDD80003DDDDA000007DDDDC0000ADDDDDDDDD
DDDDDDD10008D400010001DDDDDDDB0000CDDD2000000CDDD80001DDDDDDDDDD
DDDDDD80000CD900000004DDDDDDDD1000ADD700000006DDD30005DDDDDDDDDD
DDDDDD30005DDD20000007DDDDDDDD30007DC100000000BDC00009DDDDDDDDDD
DDDDDB0000ADDD7000000BDDDDDDDD60004D50000A10005D80000DDDDDDDDDDD
DDDDD60002DDDDC000001DDDDDDDDDA0000A00006D70000A40005DDDDDDDDDDD
DDDDC10007DDDDD500005DDDDDDDDDC000010001CDD2000300009DDDDDDDDDDD
DDDD80000CDDDDDB00008DDDDDDDDDD200000008DDD800000000CDDDDDDDDDDD
DDDD30005DDDDDDD4000BDDDDDDDDDD60000003DDDDD30000004DDDDDDDDDDDD
DDDB0000ADDDDDDD9002DDDDDDDDDDD9000000BDDDDDA0000008DDDDDDDDDDDD
DDD60002DDDDDDDDD205DDDDDDDDDDDC000006DDDDDDD300000CDDDDDDDDDDDD
DDD10007DDDDDDDDD709DDDDDDDDDDDD10001CDDDDDDDB00003DDDDDDDDDDDDD
DD80000CDDDDDDDDDC1CDDDDDDDDDDDD40008DDDDDDDDD50007DDDDDDDDDDDDD
DD30005DDDDDDDDDDD8DDDDDDDDDDDDD8003DDDDDDDDDDB000CDDDDDDDDDDDDD
DB0000ADDDDDDDDDDDDDDDDDDDDDDDDDB00ADDDDDDDDDDD603DDDDDDDDDDDDDD
D50002DDDDDDDDDDDDDDDDDDDDDDDDDDD15DDDDDDDDDDDDC17DDDDDDDDDDDDDD
C10007DDDDDDDDDDDDDDDDDDDDDDDDDDD4CDDDDDDDDDDDDD7BDDDDDDDDDDDDDD
80000CDDDDDDDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
30005DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0000ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0002DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
0007DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
000CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
005DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
00ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
02DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
}

!define OCI_MONITORING(_color)                                 SPRITE_PUT(          OCI_MONITORING          oci_monitoring, _color)
!define OCI_MONITORING(_color, _scale)                         SPRITE_PUT(          OCI_MONITORING          oci_monitoring, _color, _scale)
!define OCI_MONITORING(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_MONITORING,         oci_monitoring, _color, _scale)
!define OCI_MONITORING(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_MONITORING,         oci_monitoring, _color, _scale, _shape)
!define OCI_MONITORING(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_MONITORING, _label, oci_monitoring, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_MONITORING>> White
