sprite $oci_mobile [256x256/16z] {
xTZ15K1030JG1g3_RjtT1aXU_XGGym6x--MiXRA_47v-Vdv-Vdv-Vdv-Vdv-VlwuO5YtkZ_lDzs_Z_Jpyw_Zdlzpsh__VV_v-Vdv-Vdv-Vdv-Vdv-Vdv-noQ
dv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V
dv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vlq0g-_dv-Vdv-Vdv-Vdv-Vdv
-VdvWqcj_7ddWVvWM3z_tdYOFnZNqS-VzntYv-SF1fRtyxl_-Vdv_VzP__1R_-Ubf-v_tXza_vUVdpy8Fpy_Fp-_7
}

