sprite $oci_onprem [256x256/16z] {
vD013O103C100RyB_jrY0c19w-1wxIXVFd4-SJvnFcqznFd4-SJvnFd4-SJvnFd4-Poq7k9yudpYVE9yudpYVE9yudnEMWznFd4-SJvnFd4-SJvnFd4-azP3
d4-SJvnFd4-SJvnFd4-SpwJr4ESJvnFd4-SJvnFd4-SJvpDfFMpZZ_G0tnVd4-SJvnFd4-SJvsE1lZjWf0VOKPnFd4-SJvnFd4-SZmNwne2H7c1lSJvnFd4-
SJvnFd4-NjEN1upq09G7a1vmasCdsH6680243w3rkFzjiybiQUDhMFti7E4ZPkgNMPOv6VgLkqnQmzXaQsv0fiUt_fXxPzv_AB2RlzkbGnTvcKU_Fnuisldd
BrodFp9-Hl_ZbohKuITEzsZkiKtbKQntFg15pRsVeREa_R6CFDhvNlWot4YbaKb_B9ay6lXIdVkZrnyPFzLyzwF-UE4VztuFMXf0rhyolxAU_JuRMlOlFxzc
N_jfuf_z7Fr3Pucadv3sLZU0T_pVCqM__zrFpay1F-zNhukyAma_Ttv6BH_SputVdMEJmVvi8Es7mWyxB6s8dvD_LnXDVahv_AjsgX_pRpivhln4SEKd0x--
JGRok4z-MK_vuT9F9PyPIqZX8-jVBNBzctuA-P3oS-MdsKyPF_-3-zuVVNuA-O2Vas72lmnQ_1JnvNcBNyQf3n9cdvznvZyWzle1Jsu0Juc7yq7z7-tTDn82
GGm4m0-iIl__BQ5A6HvEweacf77drcpt6__0py_Fpy_Fpy_Fpy_Fpy_Fp_zm-Fdv-VdtR1hq9tv-Vdv-Vdv-Vdv-Vdv-_dXdBkJdv-Vdv-Vdvw_-p0kVuSzg
g_py_D4KCS7l_v-Vdv-Vdv-Vt_r_Vdv-Vdx7Ftv-Vdv-VlxCrgv__z_pJy-_-Fdz_pd-yVFpy_Fpyxl_pS_FBnBl3Fy5mi_Fpy_Fp__U-K_NIxDLM-Vdvszj
cJ_Yj3R3x_Z7py_Fpy_FBo8YulZ7py_Fpy_Fdwrv_Z7Ux_aNFt_XJcj3_Ov__Fpy_Fpy_3S
}

