sprite $oci_cli [256x256/16z] {
xTk5iHj168J10AIjF_ze3MDctvhsFDq53uJVCQwZ0G000000000000000000000003Fb_QzLzqTtVrJtHtT_LFT7TtzqzqTrVtJtHtL_TFT7TNzqzqTrVtJt
HtL_TFT7TNzqzqTrVtJtXq6m30A3mBAmVNNOlaNKlL5ilsZ_LDkyTkm9sT_RFn_Rw3zt46ozqqR_gODWxrtkqH-_tl_HKvzlVxbDV_oM_hNYiJ7_dpm8hkN7
_VhZb_hNxVkdkNzYgtzktpzHsZzHsZzHsZ-Vwbh-pMUgrlzpmUMBR4_V_fjhrhK1y3nx_sykstlJh_txd_S_PyFMK5tdzJzcozvrngVrFsVFreorug3-sRCr
WQqug7_sF9psQ-ntsjVrNxNzplFzRxhhNV_TNU_-Z-vwztzrrxl_ixW-YkEZk3wAuwEuFehZexW-4b_iv-i10000cDzD_m7qwzUlNxz-_VhrwzUlNpy00000
00000000000000000C1B
}

