sprite $oci_config [256x256/16z] {
xPq7ZYGn30CVO1Fy_syFsUW6TmHVNfM8SC6wK5pDmjQmFVvT6kc8Hfx5Oiz2mMUXuBD8z5aa-YmIVHOSNnARNX8SNzeW-YmulWJ7b-3uak3u4XnVWkDhi_4b
mV45nvVW-1ATNt1yBJQ-HESN75zmV8dEBpR-y8kDF_mQVZB-y6lu_ryj1S5cWLj_K7CAcZc8Pn8uit2k1_D-A3qHi2OJmeu5JIwEdOoaPsF9wUY9Xm___yf0
vvSaEhyarlU_387Z3oBnMrc0XwCg31P_5ei_YywV_-T2yUjty1l-zU_pTFlm2y0__83sjpNyz-q__A3yauU_y-mRtlxsTNAjMVeDrFvPxFOVVdDc7rdxaf_q
2WYr70E6FvHo3CZyA0D2NKS3XjyNxSyn01M1l6n_m3uuyACC21Ke0_pM4ig0iDoStqNxSmp8_2W3mg00PK1O8Lq81BuSjk1dF0p-I_ZN6TjMZpnKVwmvlztI
0Ft6k209toRodr_4ZLDR_dTrrrU0hQYuYzvrAA19GwnyZCHyK8Wplm069DhCtyM03UUtCjCA_0m3CgujZ05NUwNTxrj0jaMm1l126P29e0RSyQzs_0eB1ku2
70XH--381za7Vqq7Q800HpKWlAMoIGOyL_TNjLtvtukqLm1y6YRgDEoUVq7uYUDG-44W_4PF0nQSlsw0K4QOXhq0nJJ05RxKb3-NcD80kS8c6h211u6mI9g5
v5GCeW6oGFFW0f2m3tuh55BdmHBDW516Ck0iDpy8b4y5d2900sHyimu2EWjFVfjamFkdsnZ-PIyTFDv1m0yuwa7Wy5FsmHaju4CQ85IX30WrA0DI1IaN4TPf
qx0KZ5cqWm1b79YP0YCn5W0C1oPyva503YCXu3Wmf2DH-s1cEl98F0DIGTk0z0Ua0yrg03-7GCnOG1gCWg9H8IK66WRjV4i6m80w9maquApdRkcU2q0-99Cm
qGQWer7wNBYxymE3CHcVQ40e8HaGrfdHCA81OP5aW8k0EFV643Fu0pxDW82NY-V6aDMOFrt2Jcg0rpBpFJ69Qe3juPTO1jJyo1jJZBv0sRRf_EOTXPzlXY_c
KJXbOkSL01i5s603ZeGq03qE3OjC0oIe0Ihe2ISXuVZlDGQC0SC_3K29Hg4Co8HC_gBG1kI3mGQKXMvjW0dyms_GXwXa3J-w_sqwlt7yzmQ8nw_I88m1wivl
PHMBZQHhUVZ91Yop3J2RVvjjW1iAZcyFFnhVXkFRS7mRH9y5nxVX-7P13tR0687fimCcwffzD1hz
}

