sprite $oci_key_vault [256x256/16z] {
xTq54jmm44JH0zXJ__wtJK4O5BVamFJqBrpMMpPJeoF-ESKVV_pnnnz__F777t_yySSVV_pnnnz__F777t_yyMFIOt_yySSVV_pnnnz__F777t_yySTVRLBz
ySSVV_pnnnz__F777p_BRFnhS_pnnnz__F777t_yySSVV_pnP_w7Fg1vVdviZfzVT4_mNwnozz_yBci_3pgd_Qz-7cRgvt6MVeGC_KZP-L7pyZFRpqP6VhQo
yREPl_zUFpiU_YSu0x_45wvcu7_cClFhAdxCm2-OHlYr9wkxNmHDzvUP7qwVBmE_f77snwzZSFANir-t0C1O_o-M-_dwxrzSEC2_Tfhxuuy__lZvnReGvUvV
Gskc_zFb-Vzlx3_73FDZxMUMN-VWxS_yR-RuzIU02Nv6BF_Jdm2OukU8Rx7-Yt0bIpyWN2FhlsNznrdhlyQVzRydh_-VxJ_C_7K9_6p_vkWlWM_Yrv-1kvpz
TR_pudVU_btGM_gh17nRlpwS5dxXw-fVbFs_n1z__F777t_yySSVV_p0F3-BtFq0O_sZZ__7qnpzQ9dvqJFoivUBd-qS_9nqT_TpMcy_vzrz_RnJLpzlrTFF
UzqD_RnQ0x_8lxGdo-huxpi05t_Lfi72V_B1wUy__EfexZ__ykpiBoKxVwbv-KlFoLzRkVZlsip3N_iv-Eka_luwgxk_Jkljh_EQhSVm_d0R--kLslfhYF-S
VorlOUw_X0DG6FBvBd-__gFn__llr_XmDVIpvNyynTZEltqZ06py-ctMJu3po__DsGFyAFuQvaVmU_3ZNqlj_Nnp_jNOVp9xdqzDz0Fz_F7pD_mroHz_DVBh
_FWPvTVvtdv6-NM-VADI-jTBFHdcr_bMVfrlvTVvpVtNuLTVTpz7V6k_S4D7_ydmQUNN-Vv-lgs4mVVoytmk0K2Dy0j3TlHpwAU1VxK6noW_qXIolvzZFyrQ
3Jz-Upx4_-8Qd3JiDN_yj2p-do4cy0MgCH-c-ndEPpWVXlDXE1-6ys4u7uRpuPhD1uRpGTUxDPmFYjupGJ_t6S0y0J_iAM1KCZsb3m
}

