sprite $oci_firewallrule [256x256/16z] {
xC-r0S10302n1GpxRviwTU19rnkKBzQtrjZCpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpp_2py_Fpy_FtwVx-sG_Ft-VxUVlZpQFJv8aIP9qjNU7wR7281I6
5s3Ey-r_jzr07U8P9C4nVwyGN-IsrQXAv8zDJcdZyMzGmZxty9y47J_X_n3qFFzdui_vewWkVeZzCxY-VhZedskRHdu8_V5ShVqmvvVqK3_4VcCff94VFliL
ZFv-EFKxlpWR-i7cIotzkizFVxzVWDV_-kdapo_0wwUrtvYZeLzt-ezU_lm2_BR_zTF9dr-0rqzhlp5DC__hLwx_E8dgwJVc-Hq_C9EkcL-QAi0udRczNmhz
LvR2wEUNFXOWcFe9VftwZs3kxdxiAsEdWJtzClbIBx_EIKbhmNJrAsKnEDzFbLyZPJ5uNDvfQaOiC_Irkr_lb_GxVXdyrw_d-FLZVkct6o2WlFv75-3r1vJN
_-m219JNRnIWlNyK-UlVqXLFx3V0I41L-vNeLrj_J1ddYq1-rUhzNrxIKw3gvBzE2QAC1gZsO_cDg6VxcOuwrllTzapnyqZ_2AAsyji79_-niFx-cBEl_x8b
PoMWfz-dxEOtDAb-slhr97_T_-Ls_luD4Fiff3Jozs-0s6_iKce3l7vM-_qTUlrEv4x-0D6-0M8_2VxJM0YYrlj3lh-eOQoWLlljmnzJFgJRsQyKlxU4Nkzt
3dzyAA6j_-jq6XCP6_lZV8QVNVnLzTpKFt8JNWZQmozZMCcEBVsP2Qz6jVKhIDJ7dvNHYXej_FtF0ar-FgMjlxu1A1WMFwOKe9hwzHY-zFgx5q3VZTVVkm3I
3pV0wr_ryTVd-DNPBztP09_oT_V73V1vWjxy-8G-dA6lFruBd9aYOGSlQhBvw--9x-nNWR-0Nx0IqDWVHDNvVRvVWCj1dVr6-b7gJ-1d5xVIJmC_XNxb--iR
e6RPbJ8_2VxicS3oOm0A_0Q_qa-2FtMUkOq7HW6A_JwVgSqyojv-oltivEUItwDK-7r-lPzj_5prUvHT_TpWPoRMzXlyL7_qcWjevEUoNyhvKCBOmO_ZLzA7
4jRxkUx_G0bILVkLxHy0PnJllOg-F__mCtVu_S_6x-R7ze-2zohM-vc_H13fE_X9ziT9IlswmL_mUgGolx4C-_MfK7D_mUkHolnSzoTGRlJplP_w-w5M-Rdi
vtVy1PJ5VXn_GGFK-PiqGBs_lW7g_TpYfxz_h6a0SeVlPu4VwEhVkG0LZyXszlTl0DzVqG37B_XFmu5j_N1t0mIP7kw77VnK-ziyxyxY0hn-hVKN5K3QiW6e
yKjj_Fa5k1YabB6DNrhYb--lFmaey9FlnvYseN-SHkOrm6x-E9BT_PfZU0M0QJyFz9zdnFEhm8_jv_yOxUrNhj-wht4Uj8q_841RFz_xWtHW5s3a--Nvpmbm
dry5Vdm_CzcOzLFZLuf_MZNcDZrEZ0L-RlLFRNgEB7b6Fy7lf9fgyXL-LVfFeYlztEQFDWQUxC-u8BVY7Hr9_656r_kvnPzpCRwjtzVN-ydtfxrzhS2VL80H
_PGnz5L-4lpXRnb3N-O_Klt4_cbNZPy4Vy2tdl658Zy9_e1lVsIx-li7wVp3l0cxr4-EV-hVOXcK-_dA7_Fd_GUiyFEDF-JxAn3btpzBuDj-MEZ7za_nfO06
hFNZ-cD-t02mte_f3_YnVq2jto-0puzV3hBU3uO_u0T-MEJNoOGa3UC0rFh5dKCv_Zy
}

