sprite $oci_file [256x256/16z] {
vCyt5O10040n1NddtoqpVQB-ECWuvKvZmNZKyt_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_r
l_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_zN_wd_rl_fV_Q_-L_-h_qtjsBK1m20G0C3zfuwxfq7lcxWS3jdvemG_Fpy_Fpy_Fpy_
Fpy_Ft_6KRUVdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vd__oPTFEillsJ5v-Vdv-_clV
Lty1xJy_F__5ktwsVuNv-VdvjV_y_Fo7o7l-my_Fps_zcv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V
dv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdxy5
}

