!define OCI_CONTAINERHOST(_color)                                 SPRITE_PUT(          OCI_CONTAINERHOST          oci_containerhost, _color)
!define OCI_CONTAINERHOST(_color, _scale)                         SPRITE_PUT(          OCI_CONTAINERHOST          oci_containerhost, _color, _scale)
!define OCI_CONTAINERHOST(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_CONTAINERHOST,         oci_containerhost, _color, _scale)
!define OCI_CONTAINERHOST(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_CONTAINERHOST,         oci_containerhost, _color, _scale, _shape)
!define OCI_CONTAINERHOST(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_CONTAINERHOST, _label, oci_containerhost, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_CONTAINERHOST>> White
