sprite $oci_containerhost [256x256/16z] {
xTn9jjqu38FX1LWytFzkQrAz_13coB15-ySuL-B7z0cUykk9JmS__ay6Ftxy-F7ZnuyVFtxy-F7dYpFmuyUF7pz-_FZnuyUF7pz-_FZnuwy5Ftxy-F7ZnuyV
Ftxy-CKvXaDtyyT9ngMdxUoFq36Sif4_2Xd52NLsz4SbXeCCVfVUS9Z3xzT7d9tXtK3TxzUV-xqRgFlz-dE_TGDrlral_CuDrFrMlV9RDr3t6_NQRzY0qJyM
zCBlsa3TRzHhls439dyiw8NVkO6wtwZNVki6wdwZNlkj6wZxZNhjjswWxdVgnw_zwTb0tU_JPrRyQTb0tR-YFwI-w3TiODs__FF-V_V_UFv5lnlQV_phx_jr
_y863lEVVmfwXx_-XmgFVuuOpEAFa9VR_3eIdsl-odXMVqGiy3DN_MB0qZphVlrlzrg_x1S7roPPzyyfw1t--WWMlpuyZFxgrIw_pl6S_mYHk_pZBd_EPp_c
LwDacloP3VoPHd_cxlxSnOyVF_xSo8y_ujV-UAq_ekIFU9j_ZlP7xEFFH_pnTdzE-P8_J_CLV_wOb_bhUdrRRtzDh-_hwTVJn8bRtzZV_n-W_hVg_dwjF_UB
3JJpIxtmYmtqyMkzzkiDTF1hlVGNDX2x-xLU-qiRQEBN4EtN6sZW5mZX5nzkujS0xTS7DFIB0uHV7DB8h_NQBmxguTTwxTSRQE3N-Xp2NvYeWL_fi-QN6zZR
VqXzvZZl4asRKLFTxC-i-QSPb_f_abBsNzp_6ye_wTU-_pL7-eU__wW-uEj_wgl6Kr__AV2h_ZdYTej_xVZ8o_klSNV_jNxfV9IX_reTnjH_AEXz_R_w5Fx-
XxZNwzVNE_mwJ_h7JlsV-_qHM_fj_PyMVcl_gUgd_uOVF_vZ5p_zJ_p5_j_d-w-naN_G_xpSZpzFyXr__f0t-jL8SzxbB-hrTPtzrxp_sizlUF-rhR_-_kiX
Bkthhx__AZRGox_m_glOG0z_GQ_yUWCD_0MzzkiDH0E_q4k_s40RlzPhlzX06x_MQx_OG1k_rck_s40RlzPhlzn05x_MQx_UG0E_-VtNdVs6zr_5Zu5j_OVX
_TVfr6tzgVMPOnBzbQF-uftVFwVYJzFxh_F6Adxl-z-pV_ecYtvD-ib_P_znd_xh1lrFgL_tw-6CVjv_hTyPUxt_Udt_uyZSfF-gSaF_fQ1t-lK4Fl-Sv_tq
Nx_YpxAVzr_f_-77Zt_qyjD_vVtNeF_wFZ_zJ_pw7n8E-g_VyAV8w_pqN-c_qdyjwj_VVwtdNVuZVpyz_UlwtltNWhwUe__xhoENChg__xgSqTYVbsGqzUTb
wUZFIzFDdvUdaJzDwU5FO_Rtfpbx-_E6sFrJglwyALN_zVs_8VnvOuH_tDD_51ymHGznFDN_74_wXwF_sIduyUF7Zny_VlpuyUF7Zny_VlpuyUF7Zny_Vlpu
yUF7Zny_VlpuyNyw-DyU_FZnuyUF7pz-_FZnuyUF7_yV
}

