sprite $oci_pipeline [256x256/16z] {
xTm5ZeH0443H0q2bxd_QTT_EL1XjUJ-6mnjNugnoclZv-Vdv-Vdv-VcFnpzW_Fpy_FoI94cI94cI94cI94b-_y7Fpy_Fp-_t__py_Fpy_Fpy_FpzTxcPlxt6
ztXxa-tTDVRxSrfx6-sjFS3_Ndbi5_kthlsnLSTsgJ_wzaTvR9Vwesz_LCSMb_fZTNzqvy-Ncf8V6zjEIo_svuyUuS_2dtarVtJfp_lvOmR_puxwetYExV7s
7_FwVxOVUFm_tn_T-lEadpylysVd_YpyUQa_U_RNx__QqYF-lUr__Fl_-hrvvXNysOU_bbJpwzjnsv_LUZ6UFuxui_Bla_jpRJz_hkxFmd-dxp_smhzT__7_
irD-t_-ixUVdv-Vdv-Vdv_VxVtv-Vdv-VacI94cI94cI94cIf1msVdv-Vdx-lhpy_Fpy_Fpy_Fpy_Cx_pi_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_l-mz-Vdv-
Vdv-Vdv-l__dv-Vdv-VdboH9aYH9aYH9aYH9oc7Zv-Vdv-UVtSlFpy_Fpy_Fpy__3
}

