sprite $oci_key [256x256/16z] {
xTsviIGn30HH0zWLzD_R5I5Yjlal8ZCDc8g75kVQVompCpEp9rM5eAUBIw-u-0gBhwZu2gklgFgAgg-e-egghw3wYigleFhg5Zxu0YiX7o3V7fLVmVa9d9z0
zHMSdrp0HntW2Ve0-ONe_i3v2PoVmFa9d9_0-R_lNs4V8ByTd9-CvEl__ENdyVzpusv-ps7vNmnTpkyf3yN_ScmyVo-2__tS27xU3wu9_fF50VmZ_xhVVxPv
EL__wUZunxyNsT_Fwh-NV-xN7_qNy_MVVyZYQd_ETw_cwszwXljplZlPd_HTpK_e_ZIpO7y-whdSdzFHA_tz4mp6dnnDtiVl4SbSVyz8AFxpz4V_SVhrwzUl
Nxz-_VhrwzUlNxz-Cb-__grVltxzIBx-iFqX--Mp_M7xG_RBP_j3zijd-qFsooVxvPFzyib--MI_VB9VFjOlNpxMBry-qozVldo0Nxvy-VBbovSlNxvyfbw-
VB9UFbaldwtVQBtyEthyM2EMlybylyj3vViLvjdy_Gjo_x9UldpvykNBbozVlln34fPV9Yw_K01-fmBmEnQ0txa0_0u6u7So0B-Z0VYTRJo_nmtdP__jmlQ7
xG_R7xO_R7_O_h3zqQzVl_wXKFtwzUlNhr-_VltwzUlNhr-__itqwzUlNx_-hNyaLBz-_Vhxc7xz-lNhrx-fVltwzUlVKB_-Qd7zrIBxAxQ_QloanlZDpCpC
_W4
}

