sprite $oci_policyenforcement [256x256/16z] {
xCz55aGn20NHUUIy_Q-stVkx0rNZ1BZghHfElU77Zny_VlpuyUF7Zny_VlpuyUF7Zny_VlpuyUF7Zny_VlpuyUF7Zn__dFD2-lLLCByQob7yQi-zNxqvzcjW
sQDVutBbrwIS-3MZRDsl-PdrQx4C-hLmflnQ9JD-hLInuTTg5Gj-hPW1lqOquOSR_xHV-UX-3Mh6J_l-sff_V-tDiRyEpB9_xJ75ehzEoec_piYylyxEdny_
VlpuyUF7Zny_VlpuyKkX_P8KsAzROVrw5DIlLo7zYkXlveVnD_F3-9lvOVpD_83-Stjtbnn72CG0-023IlU_RPv3AjI8nkkLcddSF_GflxQPPdfvb5_bv_j9
WP_d9qc1d-QV7ftuyVxfuOaVxr_iV4ClFnVyKFyiNl1Z_H2MYFH3M27I3s61I3-4pu_qG_ZuI3-aJ_VU_obyhxEH7y9dE_ZrFztJim5-CQ_0Z_I3H6i_qCBF
itpQtVytAlnd4SR4pugV0NuM-8v-71lYy5ZT_th-Dm13_3p6D_0VAu2s_l4p9H86_bFPwUol5s0z_wCUdsv-lG2TRp__fyRtzvE5TvhvSNR-mJ3m2mN8YOFc
d-taXQDVBo1W_bl18oGmy0i527mJluvAcl-ekuJb3Vno0SAyBmE_se2mjgL_3HIMRZR_c33srtCyCFRNazpvvrb-367DtlF_YI2_dgVt-HT4a5-FTCz_YV7h
gLgVVqGWnwydQtV-MUpvNtgwlkV_aUEUVtZgklxh7nnz_6leQEBdpru1zbG_sTXFih6VxEmdE_l9rdwszfEj_Mpj9rlxsTlFtdxszcj9u_mx8OFyknjbGloL
U07-OZXtVpsQjVz8C5__Bn_B7S0lDH3qHMcC7vjNXX_xLuB_2pSY-_3ncFjHlPBzhzBw-7M-K821N-OB1HZuLVxhmCFKFt2e05C_SAe0I__93PMEVY55Y5_d
do_WQxxkrruVuTVvvmlu4ZvbJPP_0zF7lnNTpgzBVFqwNm_lvzSPONvTaU7N4Vb-iiO7VFslv2HXwfz3xF018jOlfExuwuyilnf-DF2ZqQ-_7Z_Ch-SFy-k0
CByk2FMl2T9F0Mo-__rwwRyVYlVFQyyF1VYLBTx_FXJYvxlL5mz5-kVb5vta-FK2ylrOtG6KwvyJYBi1QE1N2lXlgWv-S14hqI_bilS_vmkWavye5X3kr_V4
qSXVBo1g_ul-IIZu0meG-85-eEIFB82z_KFm9nR0tdvw-cdWToY0jdv-d4-a_GQWw0yhWDv-VfXFH1NmcFaDxlytAe1-VfpyRg2ZVnZCVmcU_tFdFoKK43h_
hQftyQEIBdt-Om7lunyx6NlDVvNfT_xldV_y1m
}

