sprite $oci_developer [256x256/16z] {
xTf9hgL034JH1O0L-zzjAH2pwZA__1jdt3l7UkVr6FITrPFogZ-KR7Sk6V-MhNVPUfUjTz5ybwrt0VoC9-2g3tRbllXlqNmNpNVHV1VDTvhR5UwlbgBvBfhl
y0VpNJY_xd1_HVCT_c2-mp-eAznVdn3-OBx3Znz_AD_XnuyVFtxy-CFu3Zz-_7p_uSUF7pz-_FX_Nhby_FZnAvkFNyby_FYLpSUlSBwkQkpY_lTvPVFnAvhl
elakck_2-Rh3_MhcX_qFl7L0kI_-MpJVHVDTDjzbwrsqtcNpNRR-AHd_beHVFoswH4J7VSWRlYgdVyTtp1YBTprJXkBTtJEcPkfTrvoPUjSrPwRUTSqPlEbV
m8_S2zTwBKE6N-PPi0zw1kfRYkQxQBsxelakck-Y-IwQxwBvBfhlilduAvhleldk6yxuif-0olRNZmj_CD_bVlczPR_y-2kSZ__Z4H4H4H4H4L6Dx3ly-F7Z
nuyVFtxy-F7ZnuyVFtxy-F7ZnuyVFtxy-F7ZnuzVRw5-FU6lJB-UyD-P_ajlbUdN4_xAz2lRV-kjClqAy4ixdtxfAB_SpiilTufVMlCl73BF__yX-glVpVPB
w_w5usRvruReFtutq7zBU_x_FFHP_lKXMlAxCVvRslSlFVG9_hqXsl2x7-xVdg2tXb7Vxzy_NCurpFjsl_QFrTlcp37-XXE_Uww_RUivqT-xzRnd-JzZxt7D
yN_ErdECttM__0E___gsdaV-_ctyI8xqRwwzvl__gOOpdwd_V_SVijuQy3FEVplEV3HY_xFZtvbmqFvB-_vX-zyr_-h1X-s_jUS_wFh7_fV_WTU_jEu_yFhd
-jhhqElVMlCVU__3VyQEll-Xwxm_m5-PVk77xw6PVZtXhqo_dl1NfbzF-2lJhoVyDSm_BlpuWyJzpqOs7x-Y-Gv_CDzby_4hcuzVqNo7FvZlildubSt7hsY-
o-RZLpOVlqxbuwTV
}

