sprite $oci_loadbalancer [256x256/16z] {
xTitRgj148J1_3Ve-v_s6NaJ3XfSS6jouUkIbqZctlh2py_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_F_rRBhs2-
t-x-P7T_jlFptw-tk__UtS_lwz_lFzlw-Vt-v_j_zlNVp-pdz_d__Nxuaotztu__tjf_tJlx_V_xxVZv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv
-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-VaVTojio7v-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-VlwD_ytDpy_Fpy_FdzOL0xyD_Fpy_Fpy_Fpy_Fpy_Fpy_FpyzTTBz0lNeB24
FuyiTDUjNwYFIvg5kQ7ENxrGNvTcO6xehykyq3JK-QiNwkio3BGDzNNzmZKfrFav9uM1OV36LzhpiawXlYwJGDzmrTUbxvyKwlpL2_LrgGSo-GPsrjUbxvyK
wlpL2_LrgGUomFE_bY_KdrJNBvo3mZFuxsVoy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_F_1G
}

