sprite $oci_desktop [256x256/16z] {
xSy70G0X0CGm0J_mxnOHR2vLq9JBaYH9aYH9aYH9UiFxqf8aIP8aIIfNny_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_F
py_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_FpyyVb2H9aYH9
KkdUMRVy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_FpytsQb-ldv-Vdv-Vdv-Vdv-Vdv-IL9aYH9abG1
}

