sprite $oci_serverless [256x256/16z] {
vTq7Rkr638RH1RnBSF-x3Lfw24Imw6FY7_JHRTznKJ56hh-C7aPT77FFt9RUN-dzbTvVwVsLtb_f_PNUN-dzbTvVwVsLtbyX_NDSIlyCSBy_7A330JeSe5S1
FiFJFjqh7_XvGoy23DF3FEhV0fXTXddKlmOmF76OP_qB0AVwjm26vmtphdy1u5J_0i2f_WM0K_qR09Vwrm26PtmE_lv_3l3_zd-VylrB08UE_xP_1AO7LHte
tpeT_Xmu_qku7j3X01qEqE407GxGuG0T3j3X01qEqE407GxGuG0T3j3X01qEqE407GxGuG3T-m1oFEW70A1VO0Vq0m3G3m1GlmVm_Hx0zti0t-y1VBy7yFqU
mFTx0D_l0No_1_3z7i3tUm3Vxm5yV_qnRYsRMt0MbyHylmNm_HR0zri0tsy1VBy5yFqMmFTR0Dzl0No_1V3z5i3tMm3VRm5ylmNm_HR0zsi0t-y1VFy-G7zb
aFr_zGi05_jVs4zSxkzU0BZJ__Uj3m7kztSl0DpjVm7WTFyB0AVxNm0utVyOu7h_hxzlVW7WzFxl1O0J_NF9Su3Z_VN2tmRFzCyfdweN08xrBvmEt-_t5qHS
lmVm_Hx0zti0t-y1VFy70VX-3-3xFO3lhm80e1y0Y7uBuFijWE-t0BxV0lX-3-3xFO3l1mT2n_khdm3y0lqlS7pLyVhwpmO05_jdW93-6I2aVmO8wPy1Glfd
W93-6I2aVmO8wPy1GlfdW93-6I2aVmO8wPy1GlfdW83-Hm2-lruOuXuYeFyTW0Fz0C3rMm3VRm5ylmNm_HY0zsi0tSy1SBy7mFqU0FTx0Dpl0N2_1y3z7W3t
Um3Sxm5mlmSm_HpWfwv_6-O105p_EC_l0_ZrhyFy9e3ldxPsEu3o_T-pQiptJviR01peNm0uqRy0SAf_0I2W_n70_VtVqwUdzCy0vu__vlu70BQ_QjhstWNx
6S3qxuz-3l2nv__-WeZjzm2utmFWVW-0-pq0xlS0kDy3u7uFWFiz0Ext0BZV0-1-3u3xFG3kzm2ytmFuVW_W-ps0x_S0OFrJm3zU1lq00FG30D7l0No_1_3z
7i3tUm3Vxm5ylmVm_Hx0zti0t-y1VBy7yFqUmFTx0D_l0MeOe9y0rCyRtmfGuG0L3b3X01KEKE405GvGuG0L3b3X01KEKE405GvGuG0L3b3X01K0SBr_4m1K
W4jYxwp_-to5h2s0N_y90C3wtvt-Joq07EglUW00rl-lzoy0dEfV03ZLlm1mgdy1u5J_0i2ft_yB0AVw5m0k7V_L8m1m_x_j_ZM0yILgdWVzQm1rOwm1L3X0
XGDKE41b0zpldnD2-kU6bFvEx-_q_axlx_J-Jk_lzFvEx-_q_axlxyJ-EUSt
}

