sprite $oci_serverdesk [256x256/16z] {
xTmt6i80283HFOtxtzOfRR9hWFTFhC-MmXSZPv8aIP8aIP8aIP8aIPAakNNy_2tYv-Vdv-Vdv-Vdv-TlcIH9aYHfd8itTj-6z_Jpy_Fpy_Fpy_Fpy_Fpy_Fp
y_Fpy_Fpy_Fpy_FpH_fUyVFpy_Fpy_Fpy_FFdooLdv-Vdv-VdtyRz-bnNdx_FkzJEt_iKo-_zt_Uvvx-SqNyZd_y_Fpy_Fpyxd_py_Fpypl-yVFpy_FpyqUS
9lkFVlkliSZ-p_xJvz_ld-CVFpy_Fpy_l_lV_Fpy_FpyZl_y_Fpy_FpyqpPEzf-UV-pbz_oZ_UTKwlb7npz-Vdv-Vdv-zx_v-Vdv-Ht_-Fdv-Vdv-Vdz_-kq
pPFzf_sd_QVzNsw_uny_Fpy_FtzKzqU994cI94cI94cI94cI94at
}

