sprite $oci_debugging [256x256/16z] {
xTm5akGw40RX0rWPTV_JFiPLWsBj1jMV6JXazISFcLGVZ3yR5HVCvTddul1pQVgvDFrScdukd0zf-hbmFeJp8Kq_5yw7S3w4yo6S3_gZ-H3EXt0-w8_cGpWV
z4VpGNyq7_HlrC7bZUpT3_gZ-Q1Vl_vOFkZ_ulJhrwzV_-15ZUpT3qb-_Vhr-_TFltxz-lNhtwLaldxzbSpNhx-o-Vf7kB-o-Vehcw-_mla-_p72_PNDz_at
d_yiJdTa-qULpx-x_i767Kbwrpzn_HlNFtBzgxcHfdVzEzS_d8l3p-NXvthRpMoS_y5kSlNdacti4rD1Vo8kEet7xLB-j-5kk-ZdhjfEzxNjUTh6n_Vrf5sl
2h3U9HlP_5BtWdsZ6U0ZXVCXMmySsNmWd0_XV0ZdGpWVmlcGpTTFE1_2-L3lRf0z0MJx8NW2z4Fq10oo9m3zoHD0Dxz-CpCpCpCpCsFBz5-GVltwzUlNhr-_
VltwzUlNhr-_VlrrUL_irwzVltxz-ltxhr-_VltwzUlNh__qAEjRxU1Vr_JsyxJMVXPgx6UfqTNFQYtznzqTpTJN-y-tFdH7Vqqb-UjcCVwwqv7Xh_ib-EjH
_VtJYFM_kljl3nVYlmyTzNSX_eMFj3d_iOPCyZ_SP3l_ab0_AVvdsspad_dwZptzvtisp17k7-5-mlsLuDTVgNxq_z42lxM_Klqi7Fuc-8kTpd-SVnah-xW2
_9DoXT_Ap-tHgbhxw_QdJUyBy5FFQk0_Dm4D_ESc8Ep-XxdkVkwCNd_NtG-tnww_w-oVN_Wnlw-fVrqJvfyvOVxP4-QVGM7-MHJcdqcxN_yyFG41_hCJS9tu
G_vFdWtzMZ_lEHWQN-f_sy7Gz_dVV2pmMV_d_nNcPW7_2kyq0InLxVoSsFrT9c2Ttz7F6qu4qABw-RBv-YkRhx_2-LNPVFsLpTTVsNpzrPNl-c_sAm
}

