sprite $oci_vm [256x256/16z] {
xTm7Tjqm34N11KZlSF-hJNL7GYaz1kQw_YPut0lfrIn9aYH9aYH9agHpU9cM94cI94dIQjtVz_Fpy_Fpy_Fpy_Fpy_Fp9ybSVnwQwJ_pt41_NZVCdz8aVxxP
57--smX_ThNtvwBU_joehpytQ-hF_HhwyqDry-U7u_V-F_Npt-dhd-z_VF_RqR-EUJ__v6T__aqFVpdeJNsw-EjHh-SUQUIlnpqlfYQz_FN8Utr7Vt9FcNJr
vwYNL7vRVptyHj_Kln-GzFRlHnnfxjyFISRuiqh977-TamporqaPvA-padVkv-Vdv-Vdv-Vdv-Vdv-VdNp_hxxx-Q-_lllvhxpychF_QNTBElyxR_W7hlpR-
0Uk_DlvpmFwNZN_0_g-DVzB-j-eVj_-ndEhghnN_kFtVh_mZzxy_-_t_XpP-Vdv-Vdv-Vdv-_ZnKpZdgHNceepy5ESE_TlxN5wMFdx_EBQVU3Cv0VpdLs5zE
3F5NS_LdPRR_QEUlau_oiL1gxG__yw01_ZBwp61_7LG-zQ-k_fKwf_hNKFyQvgz_2NzusjU_hlrhi7-rzwyovRKsQxP_ZV6lcVxr3lpy3UBdv-Vdv-Vdv-Vd
v-Vdv-Vddv8aIP8aITBwxRslbvQVdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdvy__rbJ_Vpy_Fpy_Fpy_Fpy_Fpy_98aIP8aIVe8
}

