sprite $oci_serverrack [256x256/16z] {
xTpN0OCm30JG0G9u_sspGCxf5EdfqzINIjED5sgzQ8qlYf-Vdv-Vdv-Vdv-Vdv-Vdvz_IHF6E6I7z_M7QM6yd3zC3EFb_65g62_cvm-JmpW_Fpz__T__nVzV
IR_ZlxZoE5pTFo_-tOkVdv-Vdv-Vdv-Vdv-Vdv-VVuVR0RiM_uSxmi_Fpy_Fpy_Fpy_Fpy_Fx_eFFpy_Fpy_Fpy_Fpy_Fpy_Fx_-h_b6s-IVB66JRV9FbaV3
ya_aVopo3_Zv-Kl__cU__p_v7_B_wkPVp3QwoF_Wtxdu-Vdv-Vdv-Vdv-Vdv-VdvlwXYVlrF_Fpy_Fpy_Fpy_Fpy_Fpyhl_my_Fpy_Fpy_Fpy_Fpy_Fpy-j_
2bF24leVzR_gVoxk3ql9F-3dvvT_vF-lZR_dyT_jJCU_yW-T_xh-mS_Fpy_Fpy_Fpy_Fpy_Fpy-l_ucVdv-Vdv-Vdv-Vdv-Vdx_P1G_NV_Zv-Vdv-Vdv-Vdv
-Vdv-VdvzN-5QM5O_eV-Ptxv1_py_Fn-__aT_rNC_-kJ_v4cPFtEVkV__Fpy_Fpy_Fpy_Fpy_Fpy_Fnt
}

