sprite $oci_machinelearning [256x256/16z] {
xTnfMkGy40JX0zZvnFrF--tBDCQqD4XZgJBZFwLwWTuNHgQled9gQeaDP-AN_GtCsqATyK3pjb1_A_2bf_IILk1BZ_6b5VZIKtff2Rxq55-Y8qthCRxE9Vnw
YYzjxZzKmYz-CddxzVrszilRBs-_dFtnozilPt_yAkIFlvzVo1y_U_gVU_v7E_hHJNZxSV4pWR-L7tG9Ap_dPOID_pe73FoZY_ymzsk2F_xuuu__r6qMVYtk
Zpz-JFtnnn-_96E_vEoNdFsIir-ozilQBrdxjPF_7FuRqaR-yVyZfsQs_0USf7ty4qxGHlu9HsWZ_p7-3EtarsqM_Wc7g8XVo_Ary4VkLSSl-ZlD_ThAF_mO
EVlZbxTVplxu9SNlU_klMlxugUzdt2cgviV1JmN_jtvh4_XR-UdZr_FJnI_eHnyxyVRJdRpyySSVV_pnnnz__3Bsnny_Z_dlYp_--EEFlwVuuu-_Frz__F77
ZxC__lY9lsdgSJb6aW3Osq_ZL7S_-YUA-Udpu-gdg5zluYAUu7ykTVcfvk_Qkfw_TsjN_ylrNXs_lFtgy8k_avl_WYtZbxTVdNu1SlOB5VAhrn-_hlxNDlBB
rnz__8h_bpToXSFShmby1t_yySUlgSKVV_pnnnz__F777t_yyGzSEFw-7_JqwyVi_FgOYV-UQEH_ywnvTRzkCl4VkcjJ_zWbuiVMBsz__2S0sFe5ySUFjpz-
tFsdkHztFvP-ub__-p_d-Kz-pC_FIySE_lxQ1nVnjx9EFbRJJ_lScdxQnzRqqpwqfX-QPnRrG-ld9Qhv-tFtu-x7tG_kVd3tWxiVtFqmstzjBJ_iuOzV_sVe
rsjk_ddNcjh0hy_oyUlpNFodRZBnwpOBl-A_pS2loVvZPx-At_-9NrFzyST_cFlnziT_cFlnllsFdstzrFSptm-R-XdMmdxS_Spdmyf-vlDXPJ_p-R3Nwpy7
mzlApuJS_RZxSVVZxWTtFxZxmTqFkFi1RFtNuk-BOdu6-UEFVqJnB_qBe9e_VjGUzVpnezQew8yVjKLLFsg9kdxqFYhxqRkexKTVHtK_-YeA-Vi1OE2_9O21
_nO1BluhX9Nx7G
}

