sprite $oci_shell [64x64/16] {
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDCBDDDDDDBCDDDDDCBDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDD8006DDDD301BDDD9006DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDD3001DDDA0007DDD3000DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDD5003DDDC000ADDD6003DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDC76CDDDDA69DDDDD76CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDA8CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD9005ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD9000028CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD900000005ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD900000000028CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD90000000000005ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDB5100000000000027CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDD951000000000005DDDDA448D75DC4994444B49DDC49DDDDDDDDDDC
BDDDDDDDDDDDD951000000005DDDC0231C41DB0760333B07DDB07DDDDDDDDDDC
BDDDDDDDDDDDDDDD950000005DDDC027BD40650760789B07DDB07DDDDDDDDDDC
BDDDDDDDDDDDDDDDB62000005DDDD9300A40110760225B07DDB07DDDDDDDDDDC
BDDDDDDDDDDDDB62000000005DDDC4880741DB0760888B0588A0588CDDDDDDDC
BDDDDDDDDDB62000000000005DDDB4003C41DB07600009000090000ADDDDDDDC
BDDDDDDC6200000000000028CDDDDDDCDDCCDDCCCCCCCDCCCCDCCCCDDDDDDDDC
BDDDDDD90000000000005ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD900000000028CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD900000005ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD9000028CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDD9005ADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDB8CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDA6666666666666666666666666666BDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDD70000000000000000000000000000ADDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDD70000000000000000000000000000ADDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDD70000000000000000000000000000ADDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDB8888888888888888888888888888CDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC
ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBA
}

!define OCI_SHELL(_color)                                 SPRITE_PUT(          OCI_SHELL          oci_shell, _color)
!define OCI_SHELL(_color, _scale)                         SPRITE_PUT(          OCI_SHELL          oci_shell, _color, _scale)
!define OCI_SHELL(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_SHELL,         oci_shell, _color, _scale)
!define OCI_SHELL(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_SHELL,         oci_shell, _color, _scale, _shape)
!define OCI_SHELL(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_SHELL, _label, oci_shell, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_SHELL>> White
