!define OCI_CLI(_color)                                 SPRITE_PUT(          OCI_CLI          oci_cli, _color)
!define OCI_CLI(_color, _scale)                         SPRITE_PUT(          OCI_CLI          oci_cli, _color, _scale)
!define OCI_CLI(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_CLI,         oci_cli, _color, _scale)
!define OCI_CLI(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_CLI,         oci_cli, _color, _scale, _shape)
!define OCI_CLI(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_CLI, _label, oci_cli, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_CLI>> White
