sprite $oci_laptop [256x256/16z] {
xTUd0KCn04D1_flttpPGA2p5jkvjS68Q6oP9aYH9aYH9aYH9agHxm_ZVny_Fpy_Fpy_Fpy_Fpy_Fpy_FFnQAdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V
dv-Vdv-Vdv-Vdv-Vdv-VVwBu-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-VaNZv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdx-2dqhv
gPIVoldtsSbF4_3d7k2wkmUujw-KdqhvgPIVIlcfd7zVdVnqTl9JAJ-LybCfFvNoK_YbXLzQ-AMDdYH9aYJfRewV_plny_Fpy_Fpy_Fpyq_oH_dv-Vdv5q-I
94cI94cI94cI94al
}

