sprite $oci_function [256x256/16z] {
xC610000080WWlrr5wa2000000000000000000000000WDcvaoIwGX0AmmjGwkn_jnc-pF0lJ74Cr-a5vLDUtxmuzDTOS_6_CLklsNefpxfOG2kV-tSImWkm
u-iWvMO1Vlmyuse1FNpgNqbGeG0xVnv_TtrxVX9MNj_SB-ZdozlmTHfyUVbc_-_A4RzQSBEVh2xizz-0yxKtqDjl0FSle7VpWqDblR__qLsmt_73m_VV06KZ
ZIRteujcz_jJFkaamSlRoY_b1SBz0zcEV7PNSf1lvwVy81FasNBsdqs9yhURF-NdVfGF_5PyxZ-ioDL_FYdBz_Ihu0VyT_narbBtcFAH7wG_wEVpafUYdM_z
43xmBvHiw5-rnWfh_usI2D_Vhwj-cklN_gLxrfZj3tV_fO80Vv0VP7gtVpuA_F_L7m_uGKDIVqpoxpVy0lwMzbVxyQzRT__hxVRdT-B-T_-huCTy6RS_ztE-
PEydCPol0j_Fp_cIV_ldKGM-xl2T_NhPpw8uNohn_Vsg-ENM_lNl1YwGBDFZhn3YONyzJgLaXQiVy45or_5plq1Kuk_Wrs_NW0-I0R_PBnAIv0A-iR_opHd9
ulX5OicTDyYrENxWIoudcxS0lyyV3AZZN05-Wpz19Fnq9HdnD_IhNa43_-RREdtwVd-zr6R-mWjVBhQN7_tlpSFVaVNxey2t_y4dJxfUGITVEErs3T7gx_YB
ZeA-pHyadc-clpyk5joW1rzeTlwtfzRxNX0DPkhr3ncV_-D__ZtSFv8FVeWyuD0__p3-7ku7_5d-cEtVW_dVySUKCPmV0_Jq7QzXuqzxS2m00000CCZVUX1x
gmK00000000000000000000000002
}

