sprite $oci_containerimage [256x256/16z] {
xTm73gGm58FX0oIMxt_QRKZRyPP0U3pxLwL8ufiPUZJSKqefuO_57xyn7uW__lXj-K0tPVpnn__NVA2XF_xuWRuVGFpOMlorYZ_--EEFF_xuuuy__lZZZpz-
xJ3nQuATdx_avETli_7p90y_ltKoexMVF19pE_jvDCyMTFPh9OyS_69P4x_cowKj_1gebpVtGzJRpx_pixKViYx--BLDhzJ47t_yySSVV_pnnnz__5nO9_S_
tVspiJ_FF_ByJw_AxdujdEsVV-Vzp-3HgMXwlFyanUpEVl1RObPVFoPFo_YNhlwCVyhujun_N2_--EEFF_xuuuy__lZZZny0CCtzWBiVqzmFq39yozqFkFlX
xWVS_N3tmzqFkFlXxWVS_N3t0-v-kFlXxWVS_N3t0xmsl2u3kCu1hZE0wnpWEWEuZg89XqpXUknbFW3lJy2PV-G15nd0TSF0dKlTtEJ83Dmw0tYFm-3aNQ5s
WtU7cd5V1d2T0LmtJDo3PxM22oNFQWDNeuNbcRI5MmyJr5lH37xcnyPdme-ufN_FJw3wtv7ph0PmwR_j4wZYrlxhFu1H5QxzwuT15eThloRKWK-8LloQKdyN
N_ThK_bV-hfVuzxtIzUL7JaFqGO_q02-v0VPu9U-uCSqUCwcDw01VCcFBiyLjL_LumlN5xjGDO23Hy8lQh2BB_c11NSBFnRWBVnunR7j4N-HL-4t-r7vqBRV
3r4v_p3tpxVxIIvjrMlzFBBqywYbF_xuux-BLj_F8rS_d_HptHy_uzTfMcF_u96NVtshurzVQPhxXxcVySV_hojTwOyVyST_-LR7prlzlDGVV_pnnn__DF1N
fSN_hVY5F_xuuuy_VfcvVzRqOvSVRVmqzSS_SUJdnv6h7yNyYF_QbUB7qIx_BECVEFBqhyU56w0-VhhxEUhwDusphpS0O693_Df3_e578x_rY9zr_3JmInR7
TdyD-BUs-UTZSDq6V_7_ZE_bvx_Nmq-LRhpQpmjQyBy5heFsruftz0O_xwoodpiQ1VtSMXt_u2Czx-V3FUPdaRRxMQonoy-gtUrdzUxoywMvmjVzRD62sytF
ZYt0-_lPFmdtyzEjLyDJIYcbz14
}

