sprite $oci_monitoring [256x256/16z] {
xTrPckGW30FW0u0-tV-sSu1agd4WDaJYhJRal-skVO7g8acIzalpxLTSzZTnFqdIVlkL-VRRhyotttvblltsA_Fjjr-PRx_zudpxfPRzhShFFVmiyDjlVwTu
-qdxxTVasq-IJTnFLRxz96c_-FYJzYkFFxaNlulx2vBjr-NRRt-huxST_5Hkl_tsY_6lqThjjr-CRt-x92kFFod3jz_-QpAxTlj9--tNvTjF-slvNTnVoxUV
kVmcxW-asv_0jxzhZpzfl_Buazhjjv_Quqygjzz--wdCjz_-MdwzlsktdxG_luGkxeVzPVo2OjhMVgtnx-9-059-_kcdJlljXvY_NxAl1Ucq_zxVnVtKyTzN
9DP-D67_zMZxMSFFzqFCpm_xoOdm1Fy4FztFy_oTP3GT7_AFRCPoFpVreyY_UEDOUXFt9nIMzSHl6zcFQVxyzi_wspVyV3Z-mD5-BlSpXP_gvu7--Bw3wVO7
JjwSZw5T6VFppFRRpr9_FPzF_qhVzbF6ppL-7lAUBnxgJ_WWVsowsv5-Zlad_aJ7jPzzYP_7-gdZvpC_ilrCzVCPBS6Vm5_cvr01M_gvcR_jvSSg_oWbcyzd
yT4gkQsVUNwM-VdGlwhCGKno-wyP_Lq_D_N7utkepd5F_lYJV18VgNFO4-5d-1TLEYogQJzxA3v-rjtzJFGpWP_XnyGrHN7x0KwyktVodX9Pxlzl45FysK_y
Si3Fr_oyhkhsh_7ZLF_maLZWvzqg7V-nVugudyDyrhSVgFGpqSz1FyFvFV1QoiZMJF7_E24Q_x8VkNvoqiznFbar_ZtHtqERjzpn1rxtntPFu8VyqsydOhu_
jkbgFoD-VjtFW3-BtySxrDxsiy2FSV_i-mcvWPzrVbxMzQZgzWEB_VonyyqDF3VsJmRSRfZj3x_PAPu_xBy_DhdzQNxku1yohVNp1__sX4m_0lw9Z0YJ8Vuf
VexFEOlR3ypvCUI7Z9-tE_wAU-k9ts7I5F_gl-C7_0djp_R_4LVjxnF-QqvdtCyN_84jP_sJptCmK6kI7olzyKjaludyLJ-syECrF-AM03_5ZxFzyw2f0XvO
TlCZsP_0p_J7BSb-BF77CJZ5Zva2db1o-KL-dED7iXyl-Zddp_c9rCtQ3ypvun9rFxB67pN-kKlb-p5HmJD9Gllh_AZsntUSy3zps9_03ruszN_kAtviusUb
FnwwLVk1HVvshdz9xCG5I_a0LmG__ffZwFcHSEsNiPvdlkd7KNuSxE_FCx_GVk1fflrOnw_tOoC_3l7Z2tvmyj53FvkFcSZvSkrdiNygSQ_svnlQ5_m95mxm
bPRzj5-IRx_vzjF-2zz-MNvt-tNzzaFPRtyJzqFPRp-K_VOtSJ-K_VP3sMz_4_T3sMy_bFtsDt6_fjv-PRxzzelpyGy
}

