sprite $oci_securityscanning [256x256/16z] {
xTrTUkiW38JX1S0yi__TdllprwXVXaZ5Ss_3AnmtnPZuU9vi_IF-sT6hkO1-Jn54CjxECn_FCnxFCnxFCntFCrxFCntFCrtFiwRhUQRhUQRhUORhUQRhUGRp
trI-OVh0vJD4ls8Vd_xyyErZTzOVkNrsvOFpTAx01bqA-TLiy3jFakNvu5mWJVJWR30T-E1qF1_d__1vuhSthaa5MEzlMOCAi0FDQau18ergJ04oBMfA0KBD
APCfV6j60M8jAPKPV2kM4NpFvkEl4NVnbq26yxT0ElB1IUxYwtHym8_nL_1rCt_hPhvqCrzNyzMKp_qFFwgVpzSFuQyB-7N8E_GF_-5tN_yINCXJEAmNNvpl
FzEHlnFyGM_81VYWSFFvu53Ep_itwTzyFkjUE_wgybdlkl5TvSFEJU3hUvzzn_rkFFoWlOlu3lBpVl6kNSvt_pLUKRvdytdFEl5Tllfvpvhp5UQx4Ty1ViJl
S_uqtpFv_k2I6BSTVaA_XIyOj_L7zNd-YlF5uxd3hzvyP_cQnzVx-Aitd_l3Wv_d6_4rdu_yypTuk8gVzy_dQpG_F_pp-Nd_v4qT7ZxrlxPh4-0d_Ma-t4-Z
l_zLKmU-2vS_vvFL8_E7toxuLtS_VpO6-7tz-othFxS_vOzCaGZSAA9POFWftqssSylxmOsoXtyd-0Ryc7yTd2B8yVEtlzmQ8j_jToR8jI9yKtxUpuSVpBnT
wBSz-EEF7uwubv-NQPTQzu_pbrft0pznYVaztH_W3_U3XblxgKbT-5a_vRVr8nNZp_TBVSS_VfTu_FfhBl4_VlqZZ__nF_wZDvx7__Zx_lrx_8y__U-9eWri
-lrVi_qoOCNzZx_B_DU7lfvzSlxpdRE4QkIlRnncz_Tlq16GDdv_TvM0qdng23HnXL_vzGmAN_uY1pz-NW3Ev_xy-gSD-55_uiwsaZ-DkG9toOFh__Zmn_sy
oZktCT0EVFp1uIknfBD-aetz-G-01FYnVXrz_o70X_xKqhx4ffZ_Rcrp_vaBG8mlis5Hm0y4c8zxp_tyhHv-g93__Fkl1NsX9J21S_pzPniS51Z-y--_WoDE
-la505u31yDVc9XBNW0e-U7FRu2HvvERIzFzNq0Bk_J7zS3-Hsa--N9vPF-hKtoNSixl9DzaTas7zhzRMVw0_Gy3-bdxNsRvUJ-Vtmph--z_c-Rtt_yuhU-_
_tLQtt__yxY-__xtHJpdd2q0BK5aB1l-_WMpW-V6tNx_1B3132BmWmB4G-yjcbm0lPQL__shyr4jqGj0lV7vhSkaZlW_itApMoahm_-PKGNG-_tAJUy5z3b_
_mBebBzeMKUshvLY_lplN_CevyyMG6_Ld_Vp0eZhmtvUW9MhWDJJN-i8qkVz-G9807_UlmC5q0BwmtuB5m1F4ERz-KSyu2mD_Cb7FFN3kTzEp-yA9UotxVI-
vBkllxhRxlfM0TpLNzzkLw00xVo5RHTe0TpGxuAV5y27-0RyWXyK8CitvikX0lY0tiPyELO0n_Ksvil10ZYijsk7xfA35o2__fUElkHq0HpG5xQp2gvPilCb
-CxyK8Kl1mkGN__uzoCAVB6-ErS2CZlwEb-61IXc0NfX2xMN-NAm0FdJ_VFOF_xmvVwCEH0w_lQBV7bq0VYt98yk0F-IN6YhOGNu_qWUNG3-Bp9ehK45-0mH
Q2vU0Vw8S0D-fW1vlpPuAjkX0hmtoNSj-0dpVhtyB2QmuBI3NozF3WKAe1O5s60jF2s0OjnILtBzp9sw-BRtJllnn6luRJR61z794f17GAdrkOKQOtp6RvPZ
brce0CO9D_RYYG2VPWK-R_KPkvD-tdRWsrMSdt-uWtfE-J0wcy3c4kCBi3WVPTOLu41qCAm3svaCAO1p-QpVX3-f1AHnnwDm1inEAfOfpsW40c_SuF3M9Q0D
-tm2TlPOS6GD0hCcOseGc3IRKWJ31FGy-_YiyNBF7Fdp14vwJNu1
}

