sprite $oci_database [256x256/16z] {
vDe5ZiD040NH0unB__wdNMh1KZZfjbKbYZ1w0G-ceSLThHmvdbgEqiPBsxBN5esjx2Z64j5F9wAVpcC_dSX-EhETgc5yitq6730rlbBZApE-sipwogolpFfg
C-EhuHsC-PRuow_C-igih-HyaFF1hA_aV93pGSu7EH_aVB3xU_ad7xXpGr7dsvrc3gv09_qvFHlhzDFKQURaPBJT_qFypxzGuOTKMZzd_RGLXlpagsa_E_FN
Qvd_P-3sXywoFtzM8t_Ohnt_E37-8H__IVUYR6x-D-_FaF_2_B_L7-_wBzMGdsb_HlsSzdVV27blxrokzGQ1C5Q0yPd-kytossB_uM96KWD1anVd6W7pvtz-
_o0FmE-Vu0bu_i7pBzG9iC-_3Sy_SYTGam3iIHEm01Ze08OTGA43k0czhYEODgi9MkzqHdKPmLkXcgJl9g-cETazdBuzNB3-UiOunNr-vGVk3iR_NVC1UwJL
Qwst7B2b7KVicFSlRFl58VjNi_TYl2_SN5HjkD-2bGzO-S1r3rZvm9KF5R3Ni1xWpXl2lGEmUgXzNDv0-pK0uZjkw1x4Bv3tCaH4fE3w-gFHlzZw-XTQt_lV
z2-sllsh_QlzAro_x5_jNw7wllyGx5y7r3vGNxy9Wshl-r--_nQmyg7_THTjHp2hndt_zSb_3UtawsgwCLhRlnxj7jhbhxyRdF8VuxgrrrCEKWzjzibZnMgF
E8jSRpbzmrm_SUp3yUFF5xJzqFR-9TG4zg_TYx0oWEMw1x2y_Miunvqu0_jN-rVK4B3zwx1__JRNjxtz_2eYm_uDZVxsVs3i__It_xF_W-lR_zd_mVLz_zF-
p_xF_e-g7wZsWMeVgFQ1QX-mxMUu3G1xl_pgbzUs-Ty3iPgWeNoro__UwzGaRTzuhtck3l_Mdxq_NBFwGv-VgASqoF-MhRTUqkTCsUwzulxrTQqlxdbs7zpS
luvQnUvVT1vi_XYmye4h7nh8iqOmxXLmtGEtVWnWzm1M3m3r2L3c-yTmtTy6tZu6XFOyNnCMkUpVkEYll_qZ6Fi__UqVxH_X-lQFzezmVVj7-qVxH_l7WRMt
VxH_j7_q_KFVFxH_35ZvW9KFMFc0bG-7rUx86P0lNmSVFXkrWm7uRV_YQJoFu68Fe4EVO1h82AbQym5F-GS
}

