sprite $oci_legacymainframe [256x256/16z] {
xTr95kCW38JX0nWztV-slUfLToMs4O-K-6i97lHbdb3oHi8qEH7y-F7ZnuyVFtxy-F7ZnuyVFtxyGqraRYbufLyVMuqtzuj9CTxEBsR5U3C_VZ4jnl7Znu-_
_-F_uFclev_NVxfMETpENn_yzS6F7pz-_FZnuyUF7pz-_FZnuyTVVt7afk1_MGX-_FZnuyUF7pz-_FZnuyUFdyz_yEF7Zny_VlpuyUF7Zny_VlpuyRF-w_D9
Z-b_CluPFgp_oVZVCFrFwFyn-ldfVu0VF_vGVlf_jFFJ_uF-VxfOCJpe_u5_T_3ZnuyVFtxy-F7ZnuyVFtxy-E-dEP_rJ_ZnuyUF7pz-_FZnuyUF7pz-Flx1
Zny_VlpuyUF7Zny_VlpuVn9yc3-NniJkxy_VZ2vM6Rpy_kiVTVglVzLnMF_ixrVr3mE_GVy3Gpz-_FW7ptyd-yzy_NTjVFrxoKFrxtyeZjVb_V_xyjhx9tQs
yO_9qjpzyuLP-olAClON5UNgBwkfXt_3wukVuuzu6Jz_SJqT_34JCtzzDUx-c8sJVqajFlv5jHZxeoGc_Y4gESM_hf3J_M6v_YdmbyNG7_WBO-U_wphSVtj3
A_zzrTd-9nTLMt-syhyX7Uf_SMbryW-nkQr_mdEWFy_s3x57Ht-crEWohtnPUApEOumOkh6BeLzMhdSGqxP-DV-P8hPkvC_yAFaxryyV7vOwggchfpzJGuOu
YBz_vAsqzSSCtz-FF_1FyCtyrz7--Hi0_kZd7xF-_5r_lBhwTAx3_U7iru1c_bM03FoBzXOFokN-g_uQzEh_4UNnMlzSp_VoPxNVhVz1DT_Dd_Wh-Nx-n5yM
p_uV-8lYsl-jYE_R_s-BNnv5ZI-iguBllFvn0v_rdvqk0DP_M_d3OFs_pmNGfV_BLSTtyczghnSjBe1s_QysB7YqlG3S-__FBeepzsl2ZDxRtx__utt91Dx6
FnwLsV7_Jx8y-Fy
}

