sprite $oci_devices [256x256/16z] {
xTY5aOG054J10FQcVlxHdhkl0zElP1Lf7BBmvgToacRzVdv-Vdv-Vlxfzi_C3uFnzsp_-_iT__Zv-VddgktXv-Vdvvy3ukVdv-Vdv-Vdv-Vdv-S_M_py_Fpy
_Fpy_Fpy_Fpy_Fpy_Fpy_FnJxP-7UltFxolz_Fox4_aT_vp_NF_my_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Dd2xNxK-3dv-VdtoT-VlvVu-Vdv-Vd
v-VddwN7py_Fpy_FVoHdHNv-Vdx-_P7y_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_4kDdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V
dv-Vdv-Vdvz_-V7py_Fpy_Fpy_Fpy_Fpy_Fpj_5Jpa_A-KavFodd9-Nyf9oVbFEpw-OdU_2h5y1DkXT0jbivFodd9-NyXFz3agGKnVyGFpy_Fpy_VzFp5_w7
-Fdl
}

