sprite $oci_disk [256x256/16z] {
xTr7UkGm34JX0uZlg_lVTdQJaos1B0ZrLixKxsmt6zJVIxochVxuuuy__lZZZp_--EEFF_xuuuy__lYh5lJtrothxozSsjzVkBg_Nv_i5NxTghjVjsliNtga
flvBZzNGl_HetVnwl4v-bTJ5hx9Q-5MOlr_5cVjLdhLV6rgsVctArAzjMVgrCKE_jkRcNzgSb__IzfpyEj6oyUjG9dxDzkjSq_qoyEjen_qwt66_ZdVKBuCE
-kNG6kxNCRzCEkINJKVybsnQ9_mowe1VLctsno-pDljbrqP__39icpz-MRR97xzCs-AFNxPjyCSltwxXVfNxuvTrfVxuuvTvXVxuuvTzPVxuuzTZnL_uTltz
_DmeFxzhZfy_PEklvnUyVLS_Vsc0dx_sUZ__wEL-PllvTyR-jSEFhx-2N-1NPt_ylDQ_Xlk9F_x_QAG__lZZZpz-lTCVl-AFlvv_sVfLwy____h__vVy_t-o
V_ZjNyDl_vIpltwWz-pz7upU_uCqoIynT__NjmhUv7hUd_sVySUV_V_nnt_b_c-J_V6ltF-veFWp_m6c-sdXfyuF1VnMVl3tK-fdtUKtzuEx7rLqSm7Uv0Th
F_L-nis_lBN8rN_-wwrLsEo_jlXXqFnZVfkh7wU_tdYp7opdtxFF3uv-N4PuSyYFnn1_PlZ1xlmRzlh1pS_vavmuwkVqMMOSzdFsD3y6-h4w_u_zVd0w_v5Z
H_ek3pyd_2pfPUV_KbIzd-b-flkXmA-haPy2lzJ8JuLVwkEdn2-ryLFZLni_bFYbDdvg_58NFzJuTNNnK-ENklYXnYzryKEDN-hYfyYlBdweyKjT_53Zbxhu
uIhnIrtyG8bVVVnGuPVw-87hUR_Ko0_mk5-z_03F-gLQVr4F-gLIVtswVTbD_GzUzdI_flirtQ_fVitsnw_f_ZNShzd--3NR7x_YZp_--EEFF_xuuu-_S9xA
Rnvx-btNqV-jwNvfkbyx_HZwnRrQ-dzOSwX__pi0Dp_J_Upy3i1k_xV-xD_t3c2s_shjlt_nlDZFBVvnF_UxmJVu-LUzVHIw-sy9iFCNyFzeM5ZwA_w9jFvn
XOt__lkS0-pzL2JnBMS_XVdxeRk_M_777t_yySSVV_pnnnz__F777t_yySSVV_pnnv--
}

