sprite $oci_mediastreaming [256x256/16z] {
xC610000080WXFrj5wa20000000000000000WDcxk_FOGHW8mmMOUQR_RbD2M7qhBnBovJb9u1tB_pQKMXwf1qGnYAGE2Jn1XbGu0CwG6WG065A311HMI8K3
u0X9vHDuW46L0-04gN80dA3o0OWGLD-_0A417o4GlqeJ_1TvlzvlADKFx6yrzX1-lZw_lPyT-_NXahSBvA4fISyJu0MmmvVozOgqijCmZWoSJ6Oce2m_kAD2
zA5cDbfVNrdzadBvmMPW0Np0bvIWfyUijG4YV6_tZF43pGGAWAr-IGlhUGB_T9ZvGtTLE1yq0mf0aa2QYNpfXIvR84p01m7e_mFSoirIWCy3U1JgTC2F-NpP
RedvUPBIcm60RkUiVgKjWIq0-46EMGie0E0d_Fm0G04ah7ubBo_w0V-m0Dhv-PuRb3_YyoNWNzmVwCX10MJutSeFAWZpymDODA2J-18eW9x-XNsdyNa1WF-l
w4S2SRzqM03Slyy_m8y8rLQ_z5l_0lvZDW3W1_nlHSNzOFD7Vh_aLzplLB-TuFSRViuNs5-m3U0il-luDveETJizWBN1-A7VJl176E3QWFbzgDzl-UqEVj1h
bC1d_kTGlx4VEFZkZ_ljMdv_tM_d-5N6xv_j0BbVp0yIQEMtR_SR-bVC_mHscnb-_hTYVXtajs_t-tQ_VRlVljtls_tsjVxnJ_tFyUzU_vp_lksVwvyBht_d
_iVS_-f-_zDb_FFyump_FF-Qvv_p_7jTzlv3q_TVlCbuIhx_nFtp_Xj8hi7xZ_F-Q-ltdmtyy_vxeUy_kA7_zoyBVVzq-VTV7d_7xn_93a27-HbWll_61J1-
_unlFW38ZFynVZxusQdyWB_E-4SFw7kz0W3ZLixuPoH5dH10mX2mC_vXj_4ljs6yZjHd_5D_pUy2_1xZ7o_WHmNmVW36gt_6F-V-5kFVp_m7C_z5q_bFja6y
05R7-M_wpt_qVDhTrMx-Aru0o-uv_zdCVtVv_8Sp_-N6Bh3h_ASp_-tCVpppNxk1Vrqy_pidrFSR2ShhRID2VRxz44DzlcrWQA1dYWvyst552xuTLhJGstwY
Z1vysr574_vVUt100000WW3e_-jkf0A9000000000000000003W
}

