sprite $oci_queue [256x256/16z] {
xTq7RKHH4CLG0BFMvSys5DAJBziCZlghCnxLlZk3Ft_-_Fdpvy-VFt_-_Fdpvy__Ub2hgggggggggghsl_Bdpvy_V_xy-VFdpvy_V_xy-PzPLLLLLLLLLLNx
F_dpvy-VFt_-_Fdpvy-VFt_-_5LLLLLLpDoXzWF8-SZvkFKWvoFdezp_GUq7jH-t7xN_KFj1xSVjH-q7jH-t7xSVjH_KVjn-rFv3xGUrNtwX1hKVr7xSVjn-
r7vG-t7xKViFjH_KVjn-r7u-d9oFd8-SZq2lsF_1xSVjH-q7jH-t7xKVr7xSVjJ-_BFxDxj_Tl_i_jdzczq__OSgTlzExj_i_jdzi_itktzs_-p-sVsRtJ-x
VtR_JkxVxFxP_RFxDy3z_iVkdzq_kt-p-sVtp-xVoVsRtJ-xVtR_PlVFxf_TFxj_i_jdzqy_KEVa_itkdzs_1chP_RFxP_Vl1KoTtJ-ZlwgggdXKGd_-_Fdp
vy-VFt_-_Fdpvy-Vlwggggggggggsl_9dpz__lpvy-VFdpz__lpvtm
}

