sprite $oci_api [256x256/16z] {
xTm7ajmm44FH0r0etF-qJdJcR52NIAg4ZmhEtdxO2Js9NXP2z8aawtl2-HB-QBw4FveluSSVp9Vmum_W1nI07_-Xx0AKxCUlKl3Z3-PB-F7VLZIVhtPNV4-R
xTV9YOwbV4dj5lvrrvXHqsRoTNwUnNn9RQ9VvyTPpPVKjladt6cKB6qINvLXjjoHjpb-LMRPiyUqfVuTUrDfNT4C__J5iIXfb_jL6sJR4jykvgiunmR-s82k
IMcCrVon0LsNoXJR-Bq1NPppGqpctp_XV2cSBuNpfN2-5CwNmlbIE5yAvqlXV2cShnRk5_upmOyVF_uZri_-Wv_z7x-p-VYTpSVlR3v-P_FnEvkFtzby_Cxc
utSs7x-p-VYTpSVlR3v-P_Bnu-VwZr_uMN_nHnQ0Nz5-NltWrN_U_PPLWPwMLi17Lg0dvoZWOofGJABnFQC-jm659fol5kvNE5_2Zny_VlpuyM_OD_nN_l_T
X_hzqj_pRBy_z3l1xtVyVh3Vd_4xmF_wbauFznyV-VLiVpV9nkz0VoVXxp-9k_thedVyxb66tsdxt_-wfFr_TBxsIo7-rvS5FTTl_4DY_ACdqZ_uGlpuHysj
_971Zny_VlpEvkDtDf_tl_B-Pzx_tXEDxud6zqJZUmBmIHLm_ZtdFmTMmFa7QGNWny_vZ_Wv_n8_vn_Yny_r7p_t__Z3-1B-QBw4FveluO_cI_YZ-HB-QBw4
FveluO_cI_YZ-HB-QBw4FveluO_cI_ZZ-FZnS_t7Zvy5WFs_cd0-pt_n-PTmFg__yVcdS3xlV_Bvhpm1iuzlNtsgICdITl3FQYPSRsfZR2dWnB-gGTeclhtd
K97Y83DI-gB7bVxw9FCBc7FVMHnbUG7sR7zzbla5sBFybM5cPl61EgLfrXPWp_RNnvbVWBtNxxQEFtgktvqBchQ4FteEUwz_RC0RijlVCm6_lm0_8FZnEvcF
7x-p-VYFSB-J-VZnky37Zp-rW1RkD_wd1NyqtyOVpRUJ-JttuXFo5G
}

