sprite $oci_shell [256x256/16z] {
xTn7bbin34N11KWuR_-hTOxeH7qwmQoQkMaDhd8WKMS20000yidjrTKih0wLhxPMnyftMwj3vKSxg_h7vsTZLRz-Z__9_VeVNQtP-RrXPpNptm1khOvsUxNW
_dfVadlzEm00080S00000Ef_0000000000000010udYuu_4n7i1uX1WFOJn6Z0Sn7YN6mnYF4-E1Z4UAyL36OyLuCEFHOZoSyNWn7j1un1WFQJncoZNWAd0L
7FzKw2eu_Gt1wWyhB_uhNLjlbvdmdZW_6j3VRVRdPoFwkut-sz3-xch_3tzVllzNyvVwk-lzzKLgM7-tsLy3-xih_HdTtzqVx-zBQORqVtVjzM-Xl_bN--yR
xt_cz-SbR__l-VrvnS9bPlVdTGiN7Vpyl_lvTtH_cgFwzpx_3U_V-lpRFyRbmkU_bR_zXVYL_dGrgJ-FgkhczkU2XMt5C_fppS9B_u3-NEEdZv74--dJ_WVx
N-n_il_D_aVxN-r_jl_T-GVdNvn_SlxD-SSwXlFFJHt5_8CMVsI_-ITrAlEFQXK00000-TFqwzUlNxz-_VhrwzUlNx_-YG0000000000003WFG
}

