sprite $oci_logging [256x256/16z] {
xTp5TSHG40J00An-at-sFXh732jrzVLZxOff_Ynvd6bBNgHDt_iBPCjHmjzJpa_A-KavFodd9zry_dJp-TFDvq-Bl-fSS3_TAVNlHKU3_wso0l_mBuNy_DR_
on_lVRpgvVrfyE-ikmR_3aig_U-7dv-V_uIAd_T_lUKkAV7py_Fpy_Fpy_Fpy_CV1Vv_El_bvvzc_q-6d_z_zl_y_2SAFpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_
Fp__gR_Pmy_Fpy_Fpy_Fpy_Fpy_l_9-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdz_zJtv-Vdv-Vdv-Vdv-Vdx-4uIVdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-V
dv-Vdz_zJtv-Vdv-Vdv-Vdv-Vdx-quMVdv-Vdv-Vdv-Vdv-Vdv-Vdv-VVohyUphy_Fpy_2yf_0NtFxSc_5FdFyhzivIL-FbdAQhn7-N-MKfA_Fop59Ju-MUT
RuMVVvBXT_tdmdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-_di
}

