sprite $oci_firewall [256x256/16z] {
xDUn0G0G44Mn1M3_RTLgWClh8UNF4wjTRzpyef-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-VluP8aYH9alJzf8q-wVdv-Vdv-Vdv-Ljx
TtebBGx5O3W0hFFcd-qaCCsvbEmFcMl_Ba2FUk_oafWIklkXkn_exeVkVkZkX-v-wEw7xdxexgUx7xhxwUw7xdww-w6xd-v-kllfxeVkVZhuRslfu3SBsDz_
sq03_tq3N_TVLW7x-p7_FRo_tojWVxzLmFpClEA_Rs1kwEZPYErdOtRtgxjVtVqwax6x-zNTVpNtgxjVtVrgpfUw-zNKFx-0c8ctJxCiCGJvzQkV7dxjwAzh
BZa5xE-NuMS_VvNW5v3lhmC-usUodytzqlu5EB_DoYpW-0dp6toZWCv-ylnrlb_0yPFaD_X60Stz8z1Vv_j-DlVx1SJu3RxZl_Rs-mMa-0s-vQUxdsJ_fB2x
-aVX1xRj9zTVYUhxIV0R_EDt2mZm6tpVJu3_-0s-wsTllr_02F0RVDjFA___zP7Zdyy__iBAqHZ_VFxngx1oDi1Vvlj-7V_pX_3Iq5o_WJd-4Bxlr_7lpFVz
ElwT-RvVnxypt_Vh-BVZ-_xHt2_jKu2M-ezV4zFuqPVnDSf-f-HSlwBzw_dwywQn_kFN6tvUy_EANx5-BV4hrK-8VuJujSPlF3ZL3mO_mE_oU_lvXF_wDGMF
_9NghpVy1d-sdutyVDG_YbSzz2l9xqUWjv-dVdtApoo_0lm6l-mts_Vzym8SFu_zOnl_cks3z24_p_rAzHy_hDyDJb_sixVVu5Vz-f3_UkhdMtwU-_KXFy_z
2lOV__3z5FYnVczhNoDojF_uw_pZPvh_-1NiPxh_-0DEbl3z6FwmyJpgyHy_9Z_VV_mS_-G2Zlz3HriT__4R_7Z_O7u17phRyVXPozV44UBtYL5-Z1H1VkRx
QU2_lRB63_6FkNwY_NN6RmL0rQ-t_9hdD_X1VdxsKvuYFeByMkGtTjXzrpz-zbES8dr5-_dTVzMco3hy-NxDyrDwKujmFx_xaU2nN-_wnvF8_b-KfFdribzn
VXRw2VEl_WGeyFFyjF4NKbd-OV7tzyVnHMrBqXL-OlrNAVbylqBy-XT-4lrh2nW5VgeVtu_9N-ylvlFz8yTV9qxq6_nz_QF83_3x1TnTJh3_rkZv3Nw87zll
yzVxxv2-F_hyMwC0Wv_dlr4QVeEVuyVnxtR-UG5I7WL-d5y5YiiFzl_f_C5Vu2VwnTAHxrSS_py
}

