sprite $oci_message [256x256/16z] {
xTe5hjn048R10wojllzjemvQpdGOdkUl4fZXMmRNrW00000ujmK0000000000DJ3wTUlNxz-_VhrwzUlNxz-_Vf_2W0000000FN1EAC-6JQihVlhQbNV7d3z
w_StNavFkwcRtpkvX_JF-QyD-cinULim7k_SeR-6gMcJutQxnFGFUtnyVzqcfj9gh-twsxA_3NV_DltNrE7r_xLr_r4V7UUtF_-i5p--_wns6LljU-V--yXo
zplt7_V0gw6_xT9_tWB7zNRjFrTFyAc_Dkm_5hT8VPrP7spLlvupxEOwzQh_sl_xQkuVJtH8UAAvlqsH6VrjQ1pgz-jloyIXFifn_ZK00000050Ffr-_Vltw
zUlNhr-_VltwzUj_CW0000000000e9uflR-YyrjqVWlFhoCvlwNtLtH-YyvlsVdwApg_HUUtwFoMdQ-_elDRT7uBpwyZER-bzrTqVelERzdv-YiwlqNdj-Zy
bfsllwBpMtH-2y-l8pc_fVTNT7wBpc_X-NM4zrTqVelERz7vBJjVVqNdjywFTbOy00000Du1
}

