sprite $oci_orchestrator [256x256/16z] {
xTjRalGc68FX1HZLk__TvZBdn7_tXyT2qlqCFAAXN3vWakOIoP6aSBx2-LAsNb8uNmhdArilAPmlXVEbR7xzBQ05v2JTl_e3Q04j8Db_zGVG0bh0fBy5-FjR
G0kW1IJxMq0Be0Ka-rj02w059FjRG0kuWWle8v7kW1RG8o3Rtm9Qm4el8DtV0juthw0ZGF-Qyuy0_L-katU0RkNG0gJxEQy0_MBEEWBqGSwv5t3fero7x01z
d1CAq5UnFmBqPSnVZzJNSTu1IqekG4CnFGAaw08q6CCT84KNeE6OxO2buLnU1KXIy0wGeWlGG8oFWANi0kJdroW_kW39e81eFxl_j-SESFJF5_3bI99l0S2z
iVpzR1fDs_EeNzR-vmjOoYv0HdxglvMNyRMOYgTVF5l0EjVFx7XNk5-oAo3TJxgVgU7gbwKVFxyOJRgVTFyQUFBgx6TWC6i_qVxwLxXV_vhwgR_--XElV-kl
d_hhF_d-L_sgVsAe-fSUoNgh7yFbht-5-oV7Ilxvrry_RlpwXmVBNlxwSUBF--l7YL__Xk52bt-_VtduqQPWucSJtyQF3N-5-tUDQC9dsuZZV3C_mtmxFwDy
Gp_cVF6M0d1Q_la2iFKpmZVsmu3Usiy0tzhFykGlnl9IFJms-83Um3-v2IwEyWC3Qs_jXvVfMSzFuZrumFMQstycDqOqy1kd_lgr--RVx4GT7trCp_Bb_aTk
8hxL_-1JX1Vw7t-CzYg_z1Fl4UpZw-SlwdKl1byzxNwHtEIZtsldxQ8Vyk-OfJxCzRnVumkbx_BepO_fMMeaZot_t4mrdIVyUdUklNuvP9zVDjdYbrN6htxb
bydbbsUc_FBD6l3BF5_wTK8-z-lmb5z_E5_XVENowozVsVpwe_drhox_txF2_Shsht2_we_arrz__VLZAfdYOxoGeJS_-4C6_BZlux1Rt_ElgIRSmkUG0jPd
3axnmmUK1OSKm9ryy4Ts_FiURiN8Vp_YTipuymddGpWVmlaGpeTmFeJp8TsF0J-kW0NH1K1q0P1Sm8Ba0lYHXFCXd0yhcmzuy_qBM91S06z8E1-ozS3AvWFP
Ue1mFcJh0SBvGBOUm41lt00MCT0RDe1LSl7p5InSeu7WdGbyPWMSb05xI0aS7pDuyni
}

