sprite $oci_cloud [256x256/16z] {
xC610000080WXFrj5wa200000000000009Yz-ggk80QY80XWf_ZJzQzpJayzJU2UsY2L0w0AVrZP3f360sayqDP3MmzjFRJr4EVJraESJvoFjXvnFd4-SJvn
Fd4-SJvnFkjFyudpYVDPVvhFcxCvlsUQK_cyU-vCFXzOEzhlFPt7vsDJP_gzl-iy__XGP_5zlBgVE9-wNzqlpgVkL_TRVvfFtQ_jNx-wNvk_VcN_-jUlxL__
nFtA_lMlt_g_i_MlV_sp5y3wrx_-Mwdk1rD_06ZhGHeFsdguqdfewo7EPz9wYFDfwp5jFk9yudpYVE9yudpg_glD9yudpcVzQJvF-AFz0CIAy-_OkmiaYs40
1A07Q1ZkVziTMw6_J9Mrm6WyxxksGFHuZbAni_owSgl8BqduCpDwFoL7_DdjHkvHtizL3la3-mtoIU_dIuxvOpl6_QpHXFLp8uVyNp_1-sN-bzinl5yM7SVz
Eln1FvxsQxNXQ_cu7tZw1f3XUxzMZcj-_cd_W6KURhYTXs_-n-efTLBptVunkH-il_u5F_3u1rWcT_qZVRNb_RpZV_Oz408N0BddNxPkX8lqf_7pj_f5VV3r
Bso1nlyW7ybJMMpL3kchI6sXj50Iy0S-KFH-X_5D0Rxu4n-eUJyMYp7EW5xyaG-Kl1-mccreHA_-nDE0zmCMmuyiWNTg0NyWtth4qUbIV_trrrz__VLpOlxa
_lhhhvypy-kldpFpww-VS_Fhvzpy-WdWhRqxA0001c4OQ03_Ul7Ht3aO_sOXzW_sF_PVtc__QV_Rsm3Q_-i_w7_el-Z_w3-b3X0FeEd_XG-W_na-G3k0smuW
jmFOwG1wkO1_FW9S0W0000000000003m
}

