sprite $oci_git [256x256/16z] {
xD073GD00CGm0hMUFzjYw1wv88XyFXaupG2Q1XU41I0iG1a0PG3I0AG1I0EG1Y0DG1g0D01f0D80f0580v0680r06e0q06a0qW2a0KW3a0OW3K0RG1n00A0D
C80136000nZ000Om0D80f0580v0680r06e0q06a0qW2a0KW3a0OW3K0QW3G0QG3I07TFNjkx4_E6GY28mGNOywd_RbD432iONWFPNxbjZYJ9yIj4VZNaeG5-
EEI90Nuxv741ake0INM0f3f0KXqWgGwG50GO6JB-02JL0UBqvmQ-Fq2y_WpmLVuCy5N-gFbVGMBlRXP_W9pWp-cRUJwRCbityoJA03d7dm6-ofy1lieV9J-V
WTGYVhBnWndvuSG0INM0hFJx0oJL0PBg04brWAGwG58T8AaEa8KF_W1P-zW3PAy_iW3PxNS5o7Q_Aa06_A806V2B0cJ2xmcG4RycG6RybW0Pyai2PChl290n
lo90vlo601dq2m94u1yC485_C404_i5DKn7u1pTDHU0VN2iSWNzmkNm4_i404VW70yJWdmiGXNyiG1p-gG2H-6S2-FrPwu_5FnB0xtz-M1U0TFjpll_vd__v
gVC___F_dq-p__a_vNxWYlz_lkN-_yoWz-Vv5_91xy_YuvZq_hLyiFkpbWzsVzRomUxFMZxO_LdB1xi_MNorkjwVhEI3tvyiFIXFx_SlWFJxfUj_5NoutQzT
_o_Xmyr-yVuV3HzkzQlt_uduSADVllzNnOVR_Fhz_p8-tEJ7V_w7ZWy3VXCV1lm2_inGHZxid4d8Xvqp2VcmSwQlZmyxPnBoGV3wOyy1g48-x9nfWcyQoiY7
ZKCP-I3mjno0Fy1_zp-y-pyqWrdv8F0NN83qRRy0Qu3_xdzxz_-z-n_V_P-60UNyT_ylwFpl0cmu8e20xmwmYAy98E0B0WZuWW02lY3005yGGC1t_HRu3l15
0JB0r_mla9pAXmm-69voFfJpePmFvNmevqCv7yhvKCw7SZwKyw6S3-LyAET3EH_A-L3EXt8-bFEXd0_bV2ZdGpaVolbGpeToFfJpePmFvNmevqCv7yhvKCw7
SZwKyw6S3-LyAET3EH_A-L3EXt8-bFEXd0_bV2ZdGpaVolbGpeToFfJpePmFbFEXMm-0Gly7
}

