sprite $oci_distribution [256x256/16z] {
xDZ9KSL030RX071Nvvyj9yweIeX_F7fzz_9vjxmpS7C0o_cmd0_B-R2S3ylvi9mFo_cmd0_B-R2S3ylvi9mFo_cmd0_B-R2S3ylvi9mFo_cmd0_B-H0THUVv
aF33CNn8y85J-93nmo5yY4vZytn8-U48FgJum0byoFaXpmToV23FXwGVudn8ye4q7x9-2FCXomUoV4Zx8Sg7D1z8yY7lXo0VydmWnuSn_WFrCloJ9XEt-P-X
FU5l-zANJMRUmN_chiOty9sy7pcV_um-aSBy_73YTFup_LOwco_JVllymI4gtHv_hSq_sM-X9d_G_q-tPci3H_kjrUFt_TdJhpRMVxBVSXr-tn_dQuD_XTy6
l-_FyxN1ly9lWz_tv_dQu5_Xjy7l-_DyBVClzLlap_ZpV2tnB_PRuC_vytmjyA_sM-3F-VDyBV2lzblWp_dpV2tmh_PRu8_voVErmB_QRu4_vy_pjS2VyNk6
tm9_ngydyBN07_Bh2NuB_BazplErm1_pQzvlWJ_drpHV2_n1lwRzeac_PlcQzkjslsRvURzkzskMd_VhThzc-Nc_RlThbf_twtQ_PlbvlsxtQvQVz-jslsRv
URzkzoi0xlNhHd-_Z__ZPxSVOBiVrlhvQRiVxFVTtdsOE035G1Giu5B_tHvvYHTiBx1eNW628Jlegx2bvBv9t-_0YGidwIe_NVMxyU78HxhAJrVzpbouSv6k
yjDLVxhAJrVzwIw__v3K-xEJKi6V1lO_AlnqrPy6_1L-EkfF0_ugVy3Ft-CF-Fbx_04_Vuy_uEVlyGVy_3t-W9-_nn_my_Vu0tx-7d_0pz_Z3_ZvU_m5Ft-D
F-7dR_4d_UcgFnNu4_vqrPyAGoVywQe_LVW3_dJLdnhy1N-wwa-FJTptfmF-oWx4lZyTy5VMeFRzwO2_iWcvxqy7_9Lbw7r_kkR_7V1rn9yE-Nz7V5tofwl-
b56t_EcgFsNIbhyMloH9aYH9qiUZ5LwIAepQ-FwdC6hNpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fp_yD
}

