sprite $oci_customer [256x256/16z] {
xTs7bUGm40FH04Gyv9_jFO_rLkJqNg4Ia7vppLZIkskjwSqMbww4nISiFc7nYQfFL7sYwXDLdw3yHDKdA3zHzGdAJr1-yjzfQKSNTF4Jb9-W_0Jb9oW_GVcf
VYG_GVa9oazGVgeVoKzmlXRSBoW_rO_a9mzgwNmNS_aJdAyBxbVzI7wg7ybFzTSFvAVwwmVoK_trru_bQy7zelhhhx_--XUJdn3--kkll_xwww-__lhhhx_-
-ltOwg-__lhhH_4Jrrz__VMRpA-_VfFvzTTlDhz-i_drcysltsn-_MRpwpUSxmkv_qttFqfGVcBpwpUKdw3y1EKdEDzBUrlk_jUpW_8JbP-W-WJb9oW_GVc9
oazGVQBo4rIVAAS-zVpBzwFg4rQVgFY4rQU5nIUmFG7ei5fht3zaIr9Q9dNfTQQaTrfGVABg4nIV5bIVgFf4rQT5vIUiFc7roLzB6lgIoOatioGDzQ_DxsSg
JVJhM5_two0VxPVGVh7zOljrl2_VqXhDt-_N0JxRhv7-wvHVC_q-v1VRh_5-GJUsEN5PiVrhijy7bf_j5zildDzsMd2_s7wDztldHGNqEz7zgdzQs_rEOlir
sf-s-Tb-8VqUxjSflu3--lq7_Two_41__PxlL_trx_j06leFWEjFL3_t4Q3hVnRj5y0lO_aNtE_NqVtMn0xwpV7xpHRc5y1lH_SRulUxqVtMj8v-3BH-p_Tx
gzzqlwVphSq3eFizcx_VRxhVcj7ZzfQTxjy-Wi7-CvjBJ-LBeWnWprtvgytqWmRWrqcS0Io_wZhhzypb_pfewm3c-pSy4XhfrqQ_1_dr2B_fVjFzflx-9-ZV
_qJr9nrlr-EV_srBBE_rfp_dzotyz72_l-kvXv-63E3hddluwT5-VzTp4pyzo9--oxc9dtIgsquTkGUVJlddXX-0gVw47u2n_eGVWB7-HDMd2ujFM7pYuXFN
deW7lxzEgGSWJuEtrlu1
}

