sprite $oci_cli [64x64/16] {
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD049DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD00016BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD00000038DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD0000000016BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD0000000000038DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD100000000000016BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDD9510000000000005DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDD9510000000002DDDDDDDDD8449D58DDD67DDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDD9510000002DDDDDDDD70220B05DDD14DDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDC5000002DDDDDDDD13DDBD05DDD14DDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDC9400000002DDDDDDDD04DDDD05DDD14DDDDDDDDDDDDA
DDDDDDDDDDDDDDDDC9400000000002DDDDDDDD30762B0399C14DDDDDDDDDDDDA
DDDDDDDDDDDDDC9400000000000017DDDDDDDDB3005C0000814DDDDDDDDDDDDA
DDDDDDDDDDDDD000000000000039DDDDDDDDDDDDDDDDCCCCDCCDDDDDDDDDDDDA
DDDDDDDDDDDDD000000000016BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD0000000038DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD0000016BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD00038DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDD16BDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBBBBBBBBBBBBBBBBBBCDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC000000000000000000007DDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC000000000000000000007DDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC000000000000000000007DDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDC222222222222222222228DDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8
}

!define OCI_CLI(_color)                                 SPRITE_PUT(          OCI_CLI          oci_cli, _color)
!define OCI_CLI(_color, _scale)                         SPRITE_PUT(          OCI_CLI          oci_cli, _color, _scale)
!define OCI_CLI(_color, _scale, _alias)                 SPRITE_ENT(  _alias, OCI_CLI,         oci_cli, _color, _scale)
!define OCI_CLI(_color, _scale, _alias, _shape)         SPRITE_ENT(  _alias, OCI_CLI,         oci_cli, _color, _scale, _shape)
!define OCI_CLI(_color, _scale, _alias, _shape, _label) SPRITE_ENT_L(_alias, OCI_CLI, _label, oci_cli, _color, _scale, _shape)
skinparam folderBackgroundColor<<OCI_CLI>> White
