sprite $oci_invoice [256x256/16z] {
vDUf4S0m30312dRSVxVXUKd-EsvB2pKESsUBuUFHdlUh-zNzwdvrlxfVtQ_kL_Uh-zNzwdvrlxfVtQ_kL_Uh-zNzwdvrlxfVtQ_kL_Uh-zNzwdvrl-VzBlxE
VdM_kb_Th-vNzwlxrVtgVdM_kb_Th-vNzwlxnUx_PNM_kb_Th-vNzwlxrVtgVdM_kb_Th-vNzwlxrVtgVdM_kj-N_S_tl7zgvpvm8mXXA80U88ku_ssZ7Z7c
RoyiUQCEDlARtZVmy_Fpy_Fpy_Fpy_Fpy_ClEJlv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv-Oy_w9_q32FKmFoRvoaYivRmzyl-y5F_6XC8Q_jxxJaC4H0r9WdMzlVB
_cmOOYBWg_qJGaoUHuLTn2h-Mb-WZMEV4kwOtLRtzvlyhGqpuE9kjQtlxyVwpiXAePUYli7Vgx_AwiWXQYT_Vz2VMMlu_meUyaP_sz_V9_x-B_njcbTMYdtz
BVhxq_rhNly5_z1us_7lz5N-LlFoFBaqLadQm3-qdOQ0YYiTw_jRpSjDyU8-HqsRL_AtI_vTht_7ZkpVvFv7zl-4XNskkhnpBq7B-rlmn_fgMuXwjz_zRtv-
Vdv-Vdv-Vdv-Vdv-Vlx-uUaJVdv-Vdv-Vdv-Vdv-Vdx-b__Hcv-Vdv-Vdv-Vdv-Vdv-Vdv-Vdv_V_Lz-Vdv-Vdv-Vdv-Vdv-VjV__Fpy_Fpy_Fpy_Fpy_Fpy
_Fpy_Ev_ylFpy_Fpy_Fpy_Fpy_FpBpFny_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fpy_Fp_m8
}

