sprite $oci_supportpersonnel [256x256/16z] {
xPr9ceGX24CFeFcy_srxtqCDQQKGNlP1NesA-BkYXP1-LNDygJc-17zhV0b--1lZI_33tnXVWX_-nlWI_7zQRqBSp7_FX-CXY5xGGzjL7t2F_x7fhk_t1lwh
VX-VqEWbFN7Szkjky5zQ9tm2f1zwRBXjYl0OIE_flZA10jKSNsgEBpN7bvhZIytn9VXRuqjj-U7d-my____mC_-5d_KV_DG_uAV-Tnc_uQnI09w6Epd--c_-
q_3V-08S270H_u4GfRfx0l7Z-MktI6rAl0Y_d_VKOuqQ-FuBS2L_GAZC-BNRPBKxuMBbxoD1bGi-db_I3V3IoTXA3U-dE5ClY0FA5PbB8ah7hyJufahmmvzk
65_mmmy__55vtSCFF_pmmmy__F0p_u4VVlZXf_u5_umOHBth_tC5AnL_-eRFaz5hRW07m_lw87_X1f1o1y3sXgF_3Vww_Pz5-tzdW_xdWFxtkJZ_KFNyoon_
_aS78cJ3Dyylj3d_9-ronulphvn_vlmx_3p_0dwUVmC_px-2V_BylsZ1p_DVuUVp3p___yn_MVzH_w3-L-a5MAKsGAn-jZ8RW0tkltgGS8Fxpnxas-d-kv_f
Dhh_y6Usiz7zbp-J7OtkF_sPw_xk5eEU-u-v_nf--5EfCpxyyA_E-F33lphZmm__-Xm-GWWXX112226444B3AaN9SdccSowl7cUO3WxbkuoAf67oNJgQe5MJ
7OvfQPzh-GdwHMdVvBjqD479YE-vfZVKPjTyDIV9oKdoJV4koOXlkj8C9QyfoJVvhdasGSc9RvW2XZ9SCf8oNSCRwgnBHdp3TDGr_Q7aySUzQZhhaXN_d4at
y2kENmTTXyChExz2-MMuil0BVlWzadWN_Dh9p-SV_bcJd___rNh-btx-Vpf1rd-hy_hVByeOfe2XB5UgejnAo3zhrd_Jr__34co-_xDMuAQSPphj2jYKJJMK
jcpA3yUqjDErThcCwBRBCvrslHtSTus0eHoNTnpplwRf3UMv44888OJGplRwbTsrUtgjJxgMunh6GYbl_x_Z2cYlJ-uAgEJ4ktoJijJ_ugg60PNSC9Tb2cYl
p-qAtCcX_p_-LTDHVgNV_otH_--xT9HVPVe_rAR_9vv_rEId_r6vNF33Fyxop-Rz_-j2VlZXXnz--E677txuuOSVVlZXXnz--E7_0W
}

