sprite $oci_testing [256x256/16z] {
xC610000080WWlrr5wa20000000006RdNd1Sjs4e32_08lxzhxRlWJeArSO7d6iorC4hGqUjFeXvA1Pks_0Qjxm-_vtnPij3vq-x-4fs_rg-uyVrh-Ep-vsQ
xlT6v_Q3xiVpisJay_keSRl_uTNl37Wg0BX_xuhub_PADbVc4Alajzj-bYkiWqhuwUu7H3-EtvBwbxmM5J__la8blrUzuvzSryzNhgH-joxuAUhthzpmpu5r
_BQBv3Tcl35P_Nu4lwt-PL1-Fztz3Da_nPlllrSwl_-EDSpiGlARu_z2Gsg_MxljDzZjVvFxdQ89_gNdMMDv_MlP0lmsF7rAlzF1Yj-yrj7rO9q3q9pFQAq7
clEXEH_wwGVVqlskvUZDX-PywAs7vdoQy-cjX-PyclFfhOVcV9hpwQs7vdmwykSLQCcVrsYdv_lbRlprUa_-V4OhFQzFalTDzVUwWhysFyvVK8zo5_2Z-MQI
lpv_Hl9_qWyTWb-OHee4-Qsg_mffA2ldDsVgylfREV-S3_BxlzdOyNFujSqUR_hdawlvrnb9t__SpyfHmM-EVoc9vyG6-VsNCoMti8_snIdLuljUtlDl-Vdz
kqdDnx9_aDzljlTpmu_7J--Fsii1EFpiVdCZ-d7ukVssYUZ7uIVsspwY7uUVrc_nVdZbOuz6uyj-NlZKEyq5kf-LJqc-xcVzBvJhVTdl9nt_aY0D3d8MuyT3
BabVdtzw__I-rTUVtZ-zFqBvr-dzq_k7Vth_BFxzENJiVMOAz_umEP_0ZvXAt_Tz03flTu3U7tkC1ETVidpdGV8du-jAdl77wokT_nWt-55-Bg_yYF-1EnN-
U1xn2_eOFtvndmIB7-h7hUsJYH_ljmVyWZxG__Jh_nBuWVwdt_zDu0VwXS__17p1d_Fyhw2Fz3_y_Ty4VgJVbEJYOq61rhzm0_nI_aZ7XxPtT_WdkNl_-ca-
T5nyWvdcV4ZQ-rYPd8ESvwv-K_uvr71w_qhDFxr_Ul_mJ--VnJzyjYcrrO_tDzdki4cNbxxmVm-4Z11-lB_KETPulwWLUZycmNvXbCHFwXT6IRsVr2-CKXO_
gryOfV2J-UU3ABym_3d_tUFl0OkVoN_x-7i6Vlpv7wBEVqJgwvt_kNwId__yjmdyT7u4lx3ToTh_o7vXyP_sunOXVAkVrOy_qUWxctdzk1CDvKDcFzvC6_p2
xIps_qnjfFwPI_VpmgVGBznw5e53gjxxyh__ru2_BBWpFmro3hETEvk7Fpw7RuqFDUmnrfi_Ul3tcYRwFQS7V-_folygqK5lWoKJIGE-kH97LP7FFjldVAjU
mbQ_bj-zCEkLUr_ohsyB0h-IVuzP2fV0B-Xt1kkBdz__dnncYIR-tV6P9_E3VjxoGnU_BVbmlrDSqijlh_baFyU_b5gz_bdZ3Eta5-X5_NxcfgUdty_n7__n
7__nMxqGbyjQ-yrQ-wsr_xBMVlkzFJWM000001ZaRpsAVTKC00000000008
}

